/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.Cartes;
import org.example.myunodsl.myunodsl.Changer_de_mains;
import org.example.myunodsl.myunodsl.Couper_le_jeu;
import org.example.myunodsl.myunodsl.Cumul_Cartes;
import org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes;
import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.Plus4;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cartes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.CartesImpl#getCa <em>Ca</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.CartesImpl#getCc <em>Cc</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.CartesImpl#getJpc <em>Jpc</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.CartesImpl#getClj <em>Clj</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.CartesImpl#getCdm <em>Cdm</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.CartesImpl#getP <em>P</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CartesImpl extends MinimalEObjectImpl.Container implements Cartes
{
  /**
   * The default value of the '{@link #getCa() <em>Ca</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCa()
   * @generated
   * @ordered
   */
  protected static final String CA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCa() <em>Ca</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCa()
   * @generated
   * @ordered
   */
  protected String ca = CA_EDEFAULT;

  /**
   * The cached value of the '{@link #getCc() <em>Cc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCc()
   * @generated
   * @ordered
   */
  protected Cumul_Cartes cc;

  /**
   * The cached value of the '{@link #getJpc() <em>Jpc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJpc()
   * @generated
   * @ordered
   */
  protected Jouer_plusieurs_cartes jpc;

  /**
   * The cached value of the '{@link #getClj() <em>Clj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClj()
   * @generated
   * @ordered
   */
  protected Couper_le_jeu clj;

  /**
   * The cached value of the '{@link #getCdm() <em>Cdm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCdm()
   * @generated
   * @ordered
   */
  protected Changer_de_mains cdm;

  /**
   * The cached value of the '{@link #getP() <em>P</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getP()
   * @generated
   * @ordered
   */
  protected Plus4 p;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CartesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.CARTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCa()
  {
    return ca;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCa(String newCa)
  {
    String oldCa = ca;
    ca = newCa;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__CA, oldCa, ca));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cumul_Cartes getCc()
  {
    return cc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCc(Cumul_Cartes newCc, NotificationChain msgs)
  {
    Cumul_Cartes oldCc = cc;
    cc = newCc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__CC, oldCc, newCc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCc(Cumul_Cartes newCc)
  {
    if (newCc != cc)
    {
      NotificationChain msgs = null;
      if (cc != null)
        msgs = ((InternalEObject)cc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__CC, null, msgs);
      if (newCc != null)
        msgs = ((InternalEObject)newCc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__CC, null, msgs);
      msgs = basicSetCc(newCc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__CC, newCc, newCc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Jouer_plusieurs_cartes getJpc()
  {
    return jpc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetJpc(Jouer_plusieurs_cartes newJpc, NotificationChain msgs)
  {
    Jouer_plusieurs_cartes oldJpc = jpc;
    jpc = newJpc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__JPC, oldJpc, newJpc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJpc(Jouer_plusieurs_cartes newJpc)
  {
    if (newJpc != jpc)
    {
      NotificationChain msgs = null;
      if (jpc != null)
        msgs = ((InternalEObject)jpc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__JPC, null, msgs);
      if (newJpc != null)
        msgs = ((InternalEObject)newJpc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__JPC, null, msgs);
      msgs = basicSetJpc(newJpc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__JPC, newJpc, newJpc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Couper_le_jeu getClj()
  {
    return clj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetClj(Couper_le_jeu newClj, NotificationChain msgs)
  {
    Couper_le_jeu oldClj = clj;
    clj = newClj;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__CLJ, oldClj, newClj);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClj(Couper_le_jeu newClj)
  {
    if (newClj != clj)
    {
      NotificationChain msgs = null;
      if (clj != null)
        msgs = ((InternalEObject)clj).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__CLJ, null, msgs);
      if (newClj != null)
        msgs = ((InternalEObject)newClj).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__CLJ, null, msgs);
      msgs = basicSetClj(newClj, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__CLJ, newClj, newClj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Changer_de_mains getCdm()
  {
    return cdm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCdm(Changer_de_mains newCdm, NotificationChain msgs)
  {
    Changer_de_mains oldCdm = cdm;
    cdm = newCdm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__CDM, oldCdm, newCdm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCdm(Changer_de_mains newCdm)
  {
    if (newCdm != cdm)
    {
      NotificationChain msgs = null;
      if (cdm != null)
        msgs = ((InternalEObject)cdm).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__CDM, null, msgs);
      if (newCdm != null)
        msgs = ((InternalEObject)newCdm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__CDM, null, msgs);
      msgs = basicSetCdm(newCdm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__CDM, newCdm, newCdm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Plus4 getP()
  {
    return p;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetP(Plus4 newP, NotificationChain msgs)
  {
    Plus4 oldP = p;
    p = newP;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__P, oldP, newP);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setP(Plus4 newP)
  {
    if (newP != p)
    {
      NotificationChain msgs = null;
      if (p != null)
        msgs = ((InternalEObject)p).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__P, null, msgs);
      if (newP != null)
        msgs = ((InternalEObject)newP).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES__P, null, msgs);
      msgs = basicSetP(newP, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES__P, newP, newP));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES__CC:
        return basicSetCc(null, msgs);
      case MyunodslPackage.CARTES__JPC:
        return basicSetJpc(null, msgs);
      case MyunodslPackage.CARTES__CLJ:
        return basicSetClj(null, msgs);
      case MyunodslPackage.CARTES__CDM:
        return basicSetCdm(null, msgs);
      case MyunodslPackage.CARTES__P:
        return basicSetP(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES__CA:
        return getCa();
      case MyunodslPackage.CARTES__CC:
        return getCc();
      case MyunodslPackage.CARTES__JPC:
        return getJpc();
      case MyunodslPackage.CARTES__CLJ:
        return getClj();
      case MyunodslPackage.CARTES__CDM:
        return getCdm();
      case MyunodslPackage.CARTES__P:
        return getP();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES__CA:
        setCa((String)newValue);
        return;
      case MyunodslPackage.CARTES__CC:
        setCc((Cumul_Cartes)newValue);
        return;
      case MyunodslPackage.CARTES__JPC:
        setJpc((Jouer_plusieurs_cartes)newValue);
        return;
      case MyunodslPackage.CARTES__CLJ:
        setClj((Couper_le_jeu)newValue);
        return;
      case MyunodslPackage.CARTES__CDM:
        setCdm((Changer_de_mains)newValue);
        return;
      case MyunodslPackage.CARTES__P:
        setP((Plus4)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES__CA:
        setCa(CA_EDEFAULT);
        return;
      case MyunodslPackage.CARTES__CC:
        setCc((Cumul_Cartes)null);
        return;
      case MyunodslPackage.CARTES__JPC:
        setJpc((Jouer_plusieurs_cartes)null);
        return;
      case MyunodslPackage.CARTES__CLJ:
        setClj((Couper_le_jeu)null);
        return;
      case MyunodslPackage.CARTES__CDM:
        setCdm((Changer_de_mains)null);
        return;
      case MyunodslPackage.CARTES__P:
        setP((Plus4)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES__CA:
        return CA_EDEFAULT == null ? ca != null : !CA_EDEFAULT.equals(ca);
      case MyunodslPackage.CARTES__CC:
        return cc != null;
      case MyunodslPackage.CARTES__JPC:
        return jpc != null;
      case MyunodslPackage.CARTES__CLJ:
        return clj != null;
      case MyunodslPackage.CARTES__CDM:
        return cdm != null;
      case MyunodslPackage.CARTES__P:
        return p != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ca: ");
    result.append(ca);
    result.append(')');
    return result.toString();
  }

} //CartesImpl
