/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.Plus;
import org.example.myunodsl.myunodsl.cartes_Uno_Speciales;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>cartes Uno Speciales</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.cartes_Uno_SpecialesImpl#getCuss <em>Cuss</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.cartes_Uno_SpecialesImpl#getP <em>P</em>}</li>
 * </ul>
 *
 * @generated
 */
public class cartes_Uno_SpecialesImpl extends MinimalEObjectImpl.Container implements cartes_Uno_Speciales
{
  /**
   * The default value of the '{@link #getCuss() <em>Cuss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCuss()
   * @generated
   * @ordered
   */
  protected static final String CUSS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCuss() <em>Cuss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCuss()
   * @generated
   * @ordered
   */
  protected String cuss = CUSS_EDEFAULT;

  /**
   * The cached value of the '{@link #getP() <em>P</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getP()
   * @generated
   * @ordered
   */
  protected Plus p;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected cartes_Uno_SpecialesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.CARTES_UNO_SPECIALES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCuss()
  {
    return cuss;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCuss(String newCuss)
  {
    String oldCuss = cuss;
    cuss = newCuss;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES_UNO_SPECIALES__CUSS, oldCuss, cuss));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Plus getP()
  {
    return p;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetP(Plus newP, NotificationChain msgs)
  {
    Plus oldP = p;
    p = newP;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES_UNO_SPECIALES__P, oldP, newP);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setP(Plus newP)
  {
    if (newP != p)
    {
      NotificationChain msgs = null;
      if (p != null)
        msgs = ((InternalEObject)p).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES_UNO_SPECIALES__P, null, msgs);
      if (newP != null)
        msgs = ((InternalEObject)newP).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CARTES_UNO_SPECIALES__P, null, msgs);
      msgs = basicSetP(newP, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CARTES_UNO_SPECIALES__P, newP, newP));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES_UNO_SPECIALES__P:
        return basicSetP(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES_UNO_SPECIALES__CUSS:
        return getCuss();
      case MyunodslPackage.CARTES_UNO_SPECIALES__P:
        return getP();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES_UNO_SPECIALES__CUSS:
        setCuss((String)newValue);
        return;
      case MyunodslPackage.CARTES_UNO_SPECIALES__P:
        setP((Plus)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES_UNO_SPECIALES__CUSS:
        setCuss(CUSS_EDEFAULT);
        return;
      case MyunodslPackage.CARTES_UNO_SPECIALES__P:
        setP((Plus)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.CARTES_UNO_SPECIALES__CUSS:
        return CUSS_EDEFAULT == null ? cuss != null : !CUSS_EDEFAULT.equals(cuss);
      case MyunodslPackage.CARTES_UNO_SPECIALES__P:
        return p != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cuss: ");
    result.append(cuss);
    result.append(')');
    return result.toString();
  }

} //cartes_Uno_SpecialesImpl
