/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.Configuration;
import org.example.myunodsl.myunodsl.Equipe;
import org.example.myunodsl.myunodsl.Main;
import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.Nbjoueur;
import org.example.myunodsl.myunodsl.Nombre_de_Talons_de_depart;
import org.example.myunodsl.myunodsl.Rotation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.ConfigurationImpl#getCfg <em>Cfg</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.ConfigurationImpl#getMain <em>Main</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.ConfigurationImpl#getNbtd <em>Nbtd</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.ConfigurationImpl#getRotation <em>Rotation</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.ConfigurationImpl#getNbj <em>Nbj</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.ConfigurationImpl#getEquipe <em>Equipe</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConfigurationImpl extends MinimalEObjectImpl.Container implements Configuration
{
  /**
   * The default value of the '{@link #getCfg() <em>Cfg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCfg()
   * @generated
   * @ordered
   */
  protected static final String CFG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCfg() <em>Cfg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCfg()
   * @generated
   * @ordered
   */
  protected String cfg = CFG_EDEFAULT;

  /**
   * The cached value of the '{@link #getMain() <em>Main</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMain()
   * @generated
   * @ordered
   */
  protected Main main;

  /**
   * The cached value of the '{@link #getNbtd() <em>Nbtd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbtd()
   * @generated
   * @ordered
   */
  protected Nombre_de_Talons_de_depart nbtd;

  /**
   * The cached value of the '{@link #getRotation() <em>Rotation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRotation()
   * @generated
   * @ordered
   */
  protected Rotation rotation;

  /**
   * The cached value of the '{@link #getNbj() <em>Nbj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbj()
   * @generated
   * @ordered
   */
  protected Nbjoueur nbj;

  /**
   * The cached value of the '{@link #getEquipe() <em>Equipe</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEquipe()
   * @generated
   * @ordered
   */
  protected Equipe equipe;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConfigurationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.CONFIGURATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCfg()
  {
    return cfg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCfg(String newCfg)
  {
    String oldCfg = cfg;
    cfg = newCfg;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__CFG, oldCfg, cfg));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Main getMain()
  {
    return main;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMain(Main newMain, NotificationChain msgs)
  {
    Main oldMain = main;
    main = newMain;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__MAIN, oldMain, newMain);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMain(Main newMain)
  {
    if (newMain != main)
    {
      NotificationChain msgs = null;
      if (main != null)
        msgs = ((InternalEObject)main).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__MAIN, null, msgs);
      if (newMain != null)
        msgs = ((InternalEObject)newMain).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__MAIN, null, msgs);
      msgs = basicSetMain(newMain, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__MAIN, newMain, newMain));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nombre_de_Talons_de_depart getNbtd()
  {
    return nbtd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNbtd(Nombre_de_Talons_de_depart newNbtd, NotificationChain msgs)
  {
    Nombre_de_Talons_de_depart oldNbtd = nbtd;
    nbtd = newNbtd;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__NBTD, oldNbtd, newNbtd);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbtd(Nombre_de_Talons_de_depart newNbtd)
  {
    if (newNbtd != nbtd)
    {
      NotificationChain msgs = null;
      if (nbtd != null)
        msgs = ((InternalEObject)nbtd).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__NBTD, null, msgs);
      if (newNbtd != null)
        msgs = ((InternalEObject)newNbtd).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__NBTD, null, msgs);
      msgs = basicSetNbtd(newNbtd, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__NBTD, newNbtd, newNbtd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rotation getRotation()
  {
    return rotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRotation(Rotation newRotation, NotificationChain msgs)
  {
    Rotation oldRotation = rotation;
    rotation = newRotation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__ROTATION, oldRotation, newRotation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRotation(Rotation newRotation)
  {
    if (newRotation != rotation)
    {
      NotificationChain msgs = null;
      if (rotation != null)
        msgs = ((InternalEObject)rotation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__ROTATION, null, msgs);
      if (newRotation != null)
        msgs = ((InternalEObject)newRotation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__ROTATION, null, msgs);
      msgs = basicSetRotation(newRotation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__ROTATION, newRotation, newRotation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nbjoueur getNbj()
  {
    return nbj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNbj(Nbjoueur newNbj, NotificationChain msgs)
  {
    Nbjoueur oldNbj = nbj;
    nbj = newNbj;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__NBJ, oldNbj, newNbj);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbj(Nbjoueur newNbj)
  {
    if (newNbj != nbj)
    {
      NotificationChain msgs = null;
      if (nbj != null)
        msgs = ((InternalEObject)nbj).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__NBJ, null, msgs);
      if (newNbj != null)
        msgs = ((InternalEObject)newNbj).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__NBJ, null, msgs);
      msgs = basicSetNbj(newNbj, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__NBJ, newNbj, newNbj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Equipe getEquipe()
  {
    return equipe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEquipe(Equipe newEquipe, NotificationChain msgs)
  {
    Equipe oldEquipe = equipe;
    equipe = newEquipe;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__EQUIPE, oldEquipe, newEquipe);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEquipe(Equipe newEquipe)
  {
    if (newEquipe != equipe)
    {
      NotificationChain msgs = null;
      if (equipe != null)
        msgs = ((InternalEObject)equipe).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__EQUIPE, null, msgs);
      if (newEquipe != null)
        msgs = ((InternalEObject)newEquipe).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CONFIGURATION__EQUIPE, null, msgs);
      msgs = basicSetEquipe(newEquipe, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CONFIGURATION__EQUIPE, newEquipe, newEquipe));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyunodslPackage.CONFIGURATION__MAIN:
        return basicSetMain(null, msgs);
      case MyunodslPackage.CONFIGURATION__NBTD:
        return basicSetNbtd(null, msgs);
      case MyunodslPackage.CONFIGURATION__ROTATION:
        return basicSetRotation(null, msgs);
      case MyunodslPackage.CONFIGURATION__NBJ:
        return basicSetNbj(null, msgs);
      case MyunodslPackage.CONFIGURATION__EQUIPE:
        return basicSetEquipe(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.CONFIGURATION__CFG:
        return getCfg();
      case MyunodslPackage.CONFIGURATION__MAIN:
        return getMain();
      case MyunodslPackage.CONFIGURATION__NBTD:
        return getNbtd();
      case MyunodslPackage.CONFIGURATION__ROTATION:
        return getRotation();
      case MyunodslPackage.CONFIGURATION__NBJ:
        return getNbj();
      case MyunodslPackage.CONFIGURATION__EQUIPE:
        return getEquipe();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.CONFIGURATION__CFG:
        setCfg((String)newValue);
        return;
      case MyunodslPackage.CONFIGURATION__MAIN:
        setMain((Main)newValue);
        return;
      case MyunodslPackage.CONFIGURATION__NBTD:
        setNbtd((Nombre_de_Talons_de_depart)newValue);
        return;
      case MyunodslPackage.CONFIGURATION__ROTATION:
        setRotation((Rotation)newValue);
        return;
      case MyunodslPackage.CONFIGURATION__NBJ:
        setNbj((Nbjoueur)newValue);
        return;
      case MyunodslPackage.CONFIGURATION__EQUIPE:
        setEquipe((Equipe)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.CONFIGURATION__CFG:
        setCfg(CFG_EDEFAULT);
        return;
      case MyunodslPackage.CONFIGURATION__MAIN:
        setMain((Main)null);
        return;
      case MyunodslPackage.CONFIGURATION__NBTD:
        setNbtd((Nombre_de_Talons_de_depart)null);
        return;
      case MyunodslPackage.CONFIGURATION__ROTATION:
        setRotation((Rotation)null);
        return;
      case MyunodslPackage.CONFIGURATION__NBJ:
        setNbj((Nbjoueur)null);
        return;
      case MyunodslPackage.CONFIGURATION__EQUIPE:
        setEquipe((Equipe)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.CONFIGURATION__CFG:
        return CFG_EDEFAULT == null ? cfg != null : !CFG_EDEFAULT.equals(cfg);
      case MyunodslPackage.CONFIGURATION__MAIN:
        return main != null;
      case MyunodslPackage.CONFIGURATION__NBTD:
        return nbtd != null;
      case MyunodslPackage.CONFIGURATION__ROTATION:
        return rotation != null;
      case MyunodslPackage.CONFIGURATION__NBJ:
        return nbj != null;
      case MyunodslPackage.CONFIGURATION__EQUIPE:
        return equipe != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cfg: ");
    result.append(cfg);
    result.append(')');
    return result.toString();
  }

} //ConfigurationImpl
