/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.Cumul_Cartes;
import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.PLUS_DEUX;
import org.example.myunodsl.myunodsl.PLUS_QUATRE;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cumul Cartes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Cumul_CartesImpl#getC <em>C</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Cumul_CartesImpl#getEff <em>Eff</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Cumul_CartesImpl#getPl2 <em>Pl2</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Cumul_CartesImpl#getPl4 <em>Pl4</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Cumul_CartesImpl extends MinimalEObjectImpl.Container implements Cumul_Cartes
{
  /**
   * The default value of the '{@link #getC() <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getC()
   * @generated
   * @ordered
   */
  protected static final String C_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getC() <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getC()
   * @generated
   * @ordered
   */
  protected String c = C_EDEFAULT;

  /**
   * The default value of the '{@link #getEff() <em>Eff</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEff()
   * @generated
   * @ordered
   */
  protected static final String EFF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEff() <em>Eff</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEff()
   * @generated
   * @ordered
   */
  protected String eff = EFF_EDEFAULT;

  /**
   * The cached value of the '{@link #getPl2() <em>Pl2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPl2()
   * @generated
   * @ordered
   */
  protected PLUS_DEUX pl2;

  /**
   * The cached value of the '{@link #getPl4() <em>Pl4</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPl4()
   * @generated
   * @ordered
   */
  protected PLUS_QUATRE pl4;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Cumul_CartesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.CUMUL_CARTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getC()
  {
    return c;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setC(String newC)
  {
    String oldC = c;
    c = newC;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CUMUL_CARTES__C, oldC, c));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEff()
  {
    return eff;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEff(String newEff)
  {
    String oldEff = eff;
    eff = newEff;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CUMUL_CARTES__EFF, oldEff, eff));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PLUS_DEUX getPl2()
  {
    return pl2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPl2(PLUS_DEUX newPl2, NotificationChain msgs)
  {
    PLUS_DEUX oldPl2 = pl2;
    pl2 = newPl2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CUMUL_CARTES__PL2, oldPl2, newPl2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPl2(PLUS_DEUX newPl2)
  {
    if (newPl2 != pl2)
    {
      NotificationChain msgs = null;
      if (pl2 != null)
        msgs = ((InternalEObject)pl2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CUMUL_CARTES__PL2, null, msgs);
      if (newPl2 != null)
        msgs = ((InternalEObject)newPl2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CUMUL_CARTES__PL2, null, msgs);
      msgs = basicSetPl2(newPl2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CUMUL_CARTES__PL2, newPl2, newPl2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PLUS_QUATRE getPl4()
  {
    return pl4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPl4(PLUS_QUATRE newPl4, NotificationChain msgs)
  {
    PLUS_QUATRE oldPl4 = pl4;
    pl4 = newPl4;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.CUMUL_CARTES__PL4, oldPl4, newPl4);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPl4(PLUS_QUATRE newPl4)
  {
    if (newPl4 != pl4)
    {
      NotificationChain msgs = null;
      if (pl4 != null)
        msgs = ((InternalEObject)pl4).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CUMUL_CARTES__PL4, null, msgs);
      if (newPl4 != null)
        msgs = ((InternalEObject)newPl4).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.CUMUL_CARTES__PL4, null, msgs);
      msgs = basicSetPl4(newPl4, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.CUMUL_CARTES__PL4, newPl4, newPl4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyunodslPackage.CUMUL_CARTES__PL2:
        return basicSetPl2(null, msgs);
      case MyunodslPackage.CUMUL_CARTES__PL4:
        return basicSetPl4(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.CUMUL_CARTES__C:
        return getC();
      case MyunodslPackage.CUMUL_CARTES__EFF:
        return getEff();
      case MyunodslPackage.CUMUL_CARTES__PL2:
        return getPl2();
      case MyunodslPackage.CUMUL_CARTES__PL4:
        return getPl4();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.CUMUL_CARTES__C:
        setC((String)newValue);
        return;
      case MyunodslPackage.CUMUL_CARTES__EFF:
        setEff((String)newValue);
        return;
      case MyunodslPackage.CUMUL_CARTES__PL2:
        setPl2((PLUS_DEUX)newValue);
        return;
      case MyunodslPackage.CUMUL_CARTES__PL4:
        setPl4((PLUS_QUATRE)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.CUMUL_CARTES__C:
        setC(C_EDEFAULT);
        return;
      case MyunodslPackage.CUMUL_CARTES__EFF:
        setEff(EFF_EDEFAULT);
        return;
      case MyunodslPackage.CUMUL_CARTES__PL2:
        setPl2((PLUS_DEUX)null);
        return;
      case MyunodslPackage.CUMUL_CARTES__PL4:
        setPl4((PLUS_QUATRE)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.CUMUL_CARTES__C:
        return C_EDEFAULT == null ? c != null : !C_EDEFAULT.equals(c);
      case MyunodslPackage.CUMUL_CARTES__EFF:
        return EFF_EDEFAULT == null ? eff != null : !EFF_EDEFAULT.equals(eff);
      case MyunodslPackage.CUMUL_CARTES__PL2:
        return pl2 != null;
      case MyunodslPackage.CUMUL_CARTES__PL4:
        return pl4 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (c: ");
    result.append(c);
    result.append(", eff: ");
    result.append(eff);
    result.append(')');
    return result.toString();
  }

} //Cumul_CartesImpl
