/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.Equipe;
import org.example.myunodsl.myunodsl.MyunodslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Equipe</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.EquipeImpl#getJeu <em>Jeu</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.EquipeImpl#getEq <em>Eq</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EquipeImpl extends MinimalEObjectImpl.Container implements Equipe
{
  /**
   * The default value of the '{@link #getJeu() <em>Jeu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJeu()
   * @generated
   * @ordered
   */
  protected static final String JEU_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getJeu() <em>Jeu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJeu()
   * @generated
   * @ordered
   */
  protected String jeu = JEU_EDEFAULT;

  /**
   * The default value of the '{@link #getEq() <em>Eq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEq()
   * @generated
   * @ordered
   */
  protected static final String EQ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEq() <em>Eq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEq()
   * @generated
   * @ordered
   */
  protected String eq = EQ_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EquipeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.EQUIPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getJeu()
  {
    return jeu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJeu(String newJeu)
  {
    String oldJeu = jeu;
    jeu = newJeu;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.EQUIPE__JEU, oldJeu, jeu));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEq()
  {
    return eq;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEq(String newEq)
  {
    String oldEq = eq;
    eq = newEq;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.EQUIPE__EQ, oldEq, eq));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.EQUIPE__JEU:
        return getJeu();
      case MyunodslPackage.EQUIPE__EQ:
        return getEq();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.EQUIPE__JEU:
        setJeu((String)newValue);
        return;
      case MyunodslPackage.EQUIPE__EQ:
        setEq((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.EQUIPE__JEU:
        setJeu(JEU_EDEFAULT);
        return;
      case MyunodslPackage.EQUIPE__EQ:
        setEq(EQ_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.EQUIPE__JEU:
        return JEU_EDEFAULT == null ? jeu != null : !JEU_EDEFAULT.equals(jeu);
      case MyunodslPackage.EQUIPE__EQ:
        return EQ_EDEFAULT == null ? eq != null : !EQ_EDEFAULT.equals(eq);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (jeu: ");
    result.append(jeu);
    result.append(", eq: ");
    result.append(eq);
    result.append(')');
    return result.toString();
  }

} //EquipeImpl
