/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes;
import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.Suites;
import org.example.myunodsl.myunodsl.cartes_Uno_Speciales;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Jouer plusieurs cartes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Jouer_plusieurs_cartesImpl#getJpc <em>Jpc</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Jouer_plusieurs_cartesImpl#getS <em>S</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Jouer_plusieurs_cartesImpl#getC <em>C</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Jouer_plusieurs_cartesImpl#getNb <em>Nb</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Jouer_plusieurs_cartesImpl#getCus <em>Cus</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Jouer_plusieurs_cartesImpl extends MinimalEObjectImpl.Container implements Jouer_plusieurs_cartes
{
  /**
   * The default value of the '{@link #getJpc() <em>Jpc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJpc()
   * @generated
   * @ordered
   */
  protected static final String JPC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getJpc() <em>Jpc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJpc()
   * @generated
   * @ordered
   */
  protected String jpc = JPC_EDEFAULT;

  /**
   * The cached value of the '{@link #getS() <em>S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getS()
   * @generated
   * @ordered
   */
  protected Suites s;

  /**
   * The default value of the '{@link #getC() <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getC()
   * @generated
   * @ordered
   */
  protected static final String C_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getC() <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getC()
   * @generated
   * @ordered
   */
  protected String c = C_EDEFAULT;

  /**
   * The default value of the '{@link #getNb() <em>Nb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb()
   * @generated
   * @ordered
   */
  protected static final String NB_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNb() <em>Nb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb()
   * @generated
   * @ordered
   */
  protected String nb = NB_EDEFAULT;

  /**
   * The cached value of the '{@link #getCus() <em>Cus</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCus()
   * @generated
   * @ordered
   */
  protected cartes_Uno_Speciales cus;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Jouer_plusieurs_cartesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.JOUER_PLUSIEURS_CARTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getJpc()
  {
    return jpc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJpc(String newJpc)
  {
    String oldJpc = jpc;
    jpc = newJpc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.JOUER_PLUSIEURS_CARTES__JPC, oldJpc, jpc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Suites getS()
  {
    return s;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetS(Suites newS, NotificationChain msgs)
  {
    Suites oldS = s;
    s = newS;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.JOUER_PLUSIEURS_CARTES__S, oldS, newS);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setS(Suites newS)
  {
    if (newS != s)
    {
      NotificationChain msgs = null;
      if (s != null)
        msgs = ((InternalEObject)s).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.JOUER_PLUSIEURS_CARTES__S, null, msgs);
      if (newS != null)
        msgs = ((InternalEObject)newS).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.JOUER_PLUSIEURS_CARTES__S, null, msgs);
      msgs = basicSetS(newS, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.JOUER_PLUSIEURS_CARTES__S, newS, newS));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getC()
  {
    return c;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setC(String newC)
  {
    String oldC = c;
    c = newC;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.JOUER_PLUSIEURS_CARTES__C, oldC, c));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNb()
  {
    return nb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNb(String newNb)
  {
    String oldNb = nb;
    nb = newNb;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.JOUER_PLUSIEURS_CARTES__NB, oldNb, nb));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public cartes_Uno_Speciales getCus()
  {
    return cus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCus(cartes_Uno_Speciales newCus, NotificationChain msgs)
  {
    cartes_Uno_Speciales oldCus = cus;
    cus = newCus;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS, oldCus, newCus);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCus(cartes_Uno_Speciales newCus)
  {
    if (newCus != cus)
    {
      NotificationChain msgs = null;
      if (cus != null)
        msgs = ((InternalEObject)cus).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS, null, msgs);
      if (newCus != null)
        msgs = ((InternalEObject)newCus).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS, null, msgs);
      msgs = basicSetCus(newCus, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS, newCus, newCus));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__S:
        return basicSetS(null, msgs);
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        return basicSetCus(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__JPC:
        return getJpc();
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__S:
        return getS();
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__C:
        return getC();
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__NB:
        return getNb();
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        return getCus();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__JPC:
        setJpc((String)newValue);
        return;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__S:
        setS((Suites)newValue);
        return;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__C:
        setC((String)newValue);
        return;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__NB:
        setNb((String)newValue);
        return;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        setCus((cartes_Uno_Speciales)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__JPC:
        setJpc(JPC_EDEFAULT);
        return;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__S:
        setS((Suites)null);
        return;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__C:
        setC(C_EDEFAULT);
        return;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__NB:
        setNb(NB_EDEFAULT);
        return;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        setCus((cartes_Uno_Speciales)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__JPC:
        return JPC_EDEFAULT == null ? jpc != null : !JPC_EDEFAULT.equals(jpc);
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__S:
        return s != null;
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__C:
        return C_EDEFAULT == null ? c != null : !C_EDEFAULT.equals(c);
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__NB:
        return NB_EDEFAULT == null ? nb != null : !NB_EDEFAULT.equals(nb);
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        return cus != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (jpc: ");
    result.append(jpc);
    result.append(", c: ");
    result.append(c);
    result.append(", nb: ");
    result.append(nb);
    result.append(')');
    return result.toString();
  }

} //Jouer_plusieurs_cartesImpl
