/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.example.myunodsl.myunodsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyunodslFactoryImpl extends EFactoryImpl implements MyunodslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MyunodslFactory init()
  {
    try
    {
      MyunodslFactory theMyunodslFactory = (MyunodslFactory)EPackage.Registry.INSTANCE.getEFactory(MyunodslPackage.eNS_URI);
      if (theMyunodslFactory != null)
      {
        return theMyunodslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MyunodslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyunodslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MyunodslPackage.MODEL: return createModel();
      case MyunodslPackage.UNO: return createUno();
      case MyunodslPackage.CONFIGURATION: return createConfiguration();
      case MyunodslPackage.MAIN: return createMain();
      case MyunodslPackage.VISIBILITE: return createVisibilite();
      case MyunodslPackage.NOMBRE_DE_MAINS_DE_DEPART: return createNombre_de_mains_de_depart();
      case MyunodslPackage.NOMBRE_DE_CARTES_DE_DEPART: return createNombre_de_cartes_de_depart();
      case MyunodslPackage.NOMBRE_DE_TALONS_DE_DEPART: return createNombre_de_Talons_de_depart();
      case MyunodslPackage.ROTATION: return createRotation();
      case MyunodslPackage.NBJOUEUR: return createNbjoueur();
      case MyunodslPackage.EQUIPE: return createEquipe();
      case MyunodslPackage.DEROULEMENT: return createDeroulement();
      case MyunodslPackage.PIOCHER: return createPiocher();
      case MyunodslPackage.NOMBRE_DE_CARTE: return createNombre_de_carte();
      case MyunodslPackage.CARTES: return createCartes();
      case MyunodslPackage.CUMUL_CARTES: return createCumul_Cartes();
      case MyunodslPackage.JOUER_PLUSIEURS_CARTES: return createJouer_plusieurs_cartes();
      case MyunodslPackage.SUITES: return createSuites();
      case MyunodslPackage.CARTES_UNO_SPECIALES: return createcartes_Uno_Speciales();
      case MyunodslPackage.PLUS: return createPlus();
      case MyunodslPackage.COUPER_LE_JEU: return createCouper_le_jeu();
      case MyunodslPackage.MEME_NOMBRE: return createMeme_nombre();
      case MyunodslPackage.CHANGER_DE_MAINS: return createChanger_de_mains();
      case MyunodslPackage.SEVEN_0: return createSeven_0();
      case MyunodslPackage.PLUS4: return createPlus4();
      case MyunodslPackage.PENALITE: return createPenalite();
      case MyunodslPackage.CONTESTATIONS: return createContestations();
      case MyunodslPackage.FIN: return createFin();
      case MyunodslPackage.FIN_DE_MANCHE: return createFin_de_manche();
      case MyunodslPackage.FIN_DE_PARTIE: return createFin_de_partie();
      case MyunodslPackage.VAINQUEUR: return createVainqueur();
      case MyunodslPackage.PLUS_QUATRE: return createPLUS_QUATRE();
      case MyunodslPackage.PLUS_DEUX: return createPLUS_DEUX();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Uno createUno()
  {
    UnoImpl uno = new UnoImpl();
    return uno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Configuration createConfiguration()
  {
    ConfigurationImpl configuration = new ConfigurationImpl();
    return configuration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Main createMain()
  {
    MainImpl main = new MainImpl();
    return main;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Visibilite createVisibilite()
  {
    VisibiliteImpl visibilite = new VisibiliteImpl();
    return visibilite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nombre_de_mains_de_depart createNombre_de_mains_de_depart()
  {
    Nombre_de_mains_de_departImpl nombre_de_mains_de_depart = new Nombre_de_mains_de_departImpl();
    return nombre_de_mains_de_depart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nombre_de_cartes_de_depart createNombre_de_cartes_de_depart()
  {
    Nombre_de_cartes_de_departImpl nombre_de_cartes_de_depart = new Nombre_de_cartes_de_departImpl();
    return nombre_de_cartes_de_depart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nombre_de_Talons_de_depart createNombre_de_Talons_de_depart()
  {
    Nombre_de_Talons_de_departImpl nombre_de_Talons_de_depart = new Nombre_de_Talons_de_departImpl();
    return nombre_de_Talons_de_depart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rotation createRotation()
  {
    RotationImpl rotation = new RotationImpl();
    return rotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nbjoueur createNbjoueur()
  {
    NbjoueurImpl nbjoueur = new NbjoueurImpl();
    return nbjoueur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Equipe createEquipe()
  {
    EquipeImpl equipe = new EquipeImpl();
    return equipe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Deroulement createDeroulement()
  {
    DeroulementImpl deroulement = new DeroulementImpl();
    return deroulement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Piocher createPiocher()
  {
    PiocherImpl piocher = new PiocherImpl();
    return piocher;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nombre_de_carte createNombre_de_carte()
  {
    Nombre_de_carteImpl nombre_de_carte = new Nombre_de_carteImpl();
    return nombre_de_carte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cartes createCartes()
  {
    CartesImpl cartes = new CartesImpl();
    return cartes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cumul_Cartes createCumul_Cartes()
  {
    Cumul_CartesImpl cumul_Cartes = new Cumul_CartesImpl();
    return cumul_Cartes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Jouer_plusieurs_cartes createJouer_plusieurs_cartes()
  {
    Jouer_plusieurs_cartesImpl jouer_plusieurs_cartes = new Jouer_plusieurs_cartesImpl();
    return jouer_plusieurs_cartes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Suites createSuites()
  {
    SuitesImpl suites = new SuitesImpl();
    return suites;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public cartes_Uno_Speciales createcartes_Uno_Speciales()
  {
    cartes_Uno_SpecialesImpl cartes_Uno_Speciales = new cartes_Uno_SpecialesImpl();
    return cartes_Uno_Speciales;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Plus createPlus()
  {
    PlusImpl plus = new PlusImpl();
    return plus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Couper_le_jeu createCouper_le_jeu()
  {
    Couper_le_jeuImpl couper_le_jeu = new Couper_le_jeuImpl();
    return couper_le_jeu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Meme_nombre createMeme_nombre()
  {
    Meme_nombreImpl meme_nombre = new Meme_nombreImpl();
    return meme_nombre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Changer_de_mains createChanger_de_mains()
  {
    Changer_de_mainsImpl changer_de_mains = new Changer_de_mainsImpl();
    return changer_de_mains;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Seven_0 createSeven_0()
  {
    Seven_0Impl seven_0 = new Seven_0Impl();
    return seven_0;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Plus4 createPlus4()
  {
    Plus4Impl plus4 = new Plus4Impl();
    return plus4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Penalite createPenalite()
  {
    PenaliteImpl penalite = new PenaliteImpl();
    return penalite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Contestations createContestations()
  {
    ContestationsImpl contestations = new ContestationsImpl();
    return contestations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fin createFin()
  {
    FinImpl fin = new FinImpl();
    return fin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fin_de_manche createFin_de_manche()
  {
    Fin_de_mancheImpl fin_de_manche = new Fin_de_mancheImpl();
    return fin_de_manche;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fin_de_partie createFin_de_partie()
  {
    Fin_de_partieImpl fin_de_partie = new Fin_de_partieImpl();
    return fin_de_partie;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Vainqueur createVainqueur()
  {
    VainqueurImpl vainqueur = new VainqueurImpl();
    return vainqueur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PLUS_QUATRE createPLUS_QUATRE()
  {
    PLUS_QUATREImpl pluS_QUATRE = new PLUS_QUATREImpl();
    return pluS_QUATRE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PLUS_DEUX createPLUS_DEUX()
  {
    PLUS_DEUXImpl pluS_DEUX = new PLUS_DEUXImpl();
    return pluS_DEUX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MyunodslPackage getMyunodslPackage()
  {
    return (MyunodslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MyunodslPackage getPackage()
  {
    return MyunodslPackage.eINSTANCE;
  }

} //MyunodslFactoryImpl
