/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.Nombre_de_carte;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Nombre de carte</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Nombre_de_carteImpl#getNbc <em>Nbc</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.Nombre_de_carteImpl#getCa <em>Ca</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Nombre_de_carteImpl extends MinimalEObjectImpl.Container implements Nombre_de_carte
{
  /**
   * The default value of the '{@link #getNbc() <em>Nbc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbc()
   * @generated
   * @ordered
   */
  protected static final String NBC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNbc() <em>Nbc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbc()
   * @generated
   * @ordered
   */
  protected String nbc = NBC_EDEFAULT;

  /**
   * The default value of the '{@link #getCa() <em>Ca</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCa()
   * @generated
   * @ordered
   */
  protected static final String CA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCa() <em>Ca</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCa()
   * @generated
   * @ordered
   */
  protected String ca = CA_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Nombre_de_carteImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.NOMBRE_DE_CARTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNbc()
  {
    return nbc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbc(String newNbc)
  {
    String oldNbc = nbc;
    nbc = newNbc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.NOMBRE_DE_CARTE__NBC, oldNbc, nbc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCa()
  {
    return ca;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCa(String newCa)
  {
    String oldCa = ca;
    ca = newCa;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.NOMBRE_DE_CARTE__CA, oldCa, ca));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.NOMBRE_DE_CARTE__NBC:
        return getNbc();
      case MyunodslPackage.NOMBRE_DE_CARTE__CA:
        return getCa();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.NOMBRE_DE_CARTE__NBC:
        setNbc((String)newValue);
        return;
      case MyunodslPackage.NOMBRE_DE_CARTE__CA:
        setCa((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.NOMBRE_DE_CARTE__NBC:
        setNbc(NBC_EDEFAULT);
        return;
      case MyunodslPackage.NOMBRE_DE_CARTE__CA:
        setCa(CA_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.NOMBRE_DE_CARTE__NBC:
        return NBC_EDEFAULT == null ? nbc != null : !NBC_EDEFAULT.equals(nbc);
      case MyunodslPackage.NOMBRE_DE_CARTE__CA:
        return CA_EDEFAULT == null ? ca != null : !CA_EDEFAULT.equals(ca);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nbc: ");
    result.append(nbc);
    result.append(", ca: ");
    result.append(ca);
    result.append(')');
    return result.toString();
  }

} //Nombre_de_carteImpl
