/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.PLUS_DEUX;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PLUS DEUX</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.PLUS_DEUXImpl#getPld <em>Pld</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.PLUS_DEUXImpl#getPd <em>Pd</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PLUS_DEUXImpl extends MinimalEObjectImpl.Container implements PLUS_DEUX
{
  /**
   * The default value of the '{@link #getPld() <em>Pld</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPld()
   * @generated
   * @ordered
   */
  protected static final String PLD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPld() <em>Pld</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPld()
   * @generated
   * @ordered
   */
  protected String pld = PLD_EDEFAULT;

  /**
   * The default value of the '{@link #getPd() <em>Pd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPd()
   * @generated
   * @ordered
   */
  protected static final String PD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPd() <em>Pd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPd()
   * @generated
   * @ordered
   */
  protected String pd = PD_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PLUS_DEUXImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.PLUS_DEUX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPld()
  {
    return pld;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPld(String newPld)
  {
    String oldPld = pld;
    pld = newPld;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.PLUS_DEUX__PLD, oldPld, pld));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPd()
  {
    return pd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPd(String newPd)
  {
    String oldPd = pd;
    pd = newPd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.PLUS_DEUX__PD, oldPd, pd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.PLUS_DEUX__PLD:
        return getPld();
      case MyunodslPackage.PLUS_DEUX__PD:
        return getPd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.PLUS_DEUX__PLD:
        setPld((String)newValue);
        return;
      case MyunodslPackage.PLUS_DEUX__PD:
        setPd((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.PLUS_DEUX__PLD:
        setPld(PLD_EDEFAULT);
        return;
      case MyunodslPackage.PLUS_DEUX__PD:
        setPd(PD_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.PLUS_DEUX__PLD:
        return PLD_EDEFAULT == null ? pld != null : !PLD_EDEFAULT.equals(pld);
      case MyunodslPackage.PLUS_DEUX__PD:
        return PD_EDEFAULT == null ? pd != null : !PD_EDEFAULT.equals(pd);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (pld: ");
    result.append(pld);
    result.append(", pd: ");
    result.append(pd);
    result.append(')');
    return result.toString();
  }

} //PLUS_DEUXImpl
