/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.PLUS_QUATRE;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PLUS QUATRE</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.PLUS_QUATREImpl#getPlq <em>Plq</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.PLUS_QUATREImpl#getPq <em>Pq</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PLUS_QUATREImpl extends MinimalEObjectImpl.Container implements PLUS_QUATRE
{
  /**
   * The default value of the '{@link #getPlq() <em>Plq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlq()
   * @generated
   * @ordered
   */
  protected static final String PLQ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPlq() <em>Plq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlq()
   * @generated
   * @ordered
   */
  protected String plq = PLQ_EDEFAULT;

  /**
   * The default value of the '{@link #getPq() <em>Pq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPq()
   * @generated
   * @ordered
   */
  protected static final String PQ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPq() <em>Pq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPq()
   * @generated
   * @ordered
   */
  protected String pq = PQ_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PLUS_QUATREImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.PLUS_QUATRE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPlq()
  {
    return plq;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlq(String newPlq)
  {
    String oldPlq = plq;
    plq = newPlq;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.PLUS_QUATRE__PLQ, oldPlq, plq));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPq()
  {
    return pq;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPq(String newPq)
  {
    String oldPq = pq;
    pq = newPq;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.PLUS_QUATRE__PQ, oldPq, pq));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.PLUS_QUATRE__PLQ:
        return getPlq();
      case MyunodslPackage.PLUS_QUATRE__PQ:
        return getPq();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.PLUS_QUATRE__PLQ:
        setPlq((String)newValue);
        return;
      case MyunodslPackage.PLUS_QUATRE__PQ:
        setPq((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.PLUS_QUATRE__PLQ:
        setPlq(PLQ_EDEFAULT);
        return;
      case MyunodslPackage.PLUS_QUATRE__PQ:
        setPq(PQ_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.PLUS_QUATRE__PLQ:
        return PLQ_EDEFAULT == null ? plq != null : !PLQ_EDEFAULT.equals(plq);
      case MyunodslPackage.PLUS_QUATRE__PQ:
        return PQ_EDEFAULT == null ? pq != null : !PQ_EDEFAULT.equals(pq);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (plq: ");
    result.append(plq);
    result.append(", pq: ");
    result.append(pq);
    result.append(')');
    return result.toString();
  }

} //PLUS_QUATREImpl
