/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.myunodsl.myunodsl.MyunodslPackage;
import org.example.myunodsl.myunodsl.Vainqueur;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Vainqueur</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.VainqueurImpl#getManches <em>Manches</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.VainqueurImpl#getMoins <em>Moins</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.VainqueurImpl#getDernier <em>Dernier</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.impl.VainqueurImpl#getPlus <em>Plus</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VainqueurImpl extends MinimalEObjectImpl.Container implements Vainqueur
{
  /**
   * The default value of the '{@link #getManches() <em>Manches</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getManches()
   * @generated
   * @ordered
   */
  protected static final String MANCHES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getManches() <em>Manches</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getManches()
   * @generated
   * @ordered
   */
  protected String manches = MANCHES_EDEFAULT;

  /**
   * The default value of the '{@link #getMoins() <em>Moins</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoins()
   * @generated
   * @ordered
   */
  protected static final String MOINS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMoins() <em>Moins</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoins()
   * @generated
   * @ordered
   */
  protected String moins = MOINS_EDEFAULT;

  /**
   * The default value of the '{@link #getDernier() <em>Dernier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDernier()
   * @generated
   * @ordered
   */
  protected static final String DERNIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDernier() <em>Dernier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDernier()
   * @generated
   * @ordered
   */
  protected String dernier = DERNIER_EDEFAULT;

  /**
   * The default value of the '{@link #getPlus() <em>Plus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlus()
   * @generated
   * @ordered
   */
  protected static final String PLUS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPlus() <em>Plus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlus()
   * @generated
   * @ordered
   */
  protected String plus = PLUS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VainqueurImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyunodslPackage.Literals.VAINQUEUR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getManches()
  {
    return manches;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setManches(String newManches)
  {
    String oldManches = manches;
    manches = newManches;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.VAINQUEUR__MANCHES, oldManches, manches));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMoins()
  {
    return moins;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMoins(String newMoins)
  {
    String oldMoins = moins;
    moins = newMoins;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.VAINQUEUR__MOINS, oldMoins, moins));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDernier()
  {
    return dernier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDernier(String newDernier)
  {
    String oldDernier = dernier;
    dernier = newDernier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.VAINQUEUR__DERNIER, oldDernier, dernier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPlus()
  {
    return plus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlus(String newPlus)
  {
    String oldPlus = plus;
    plus = newPlus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyunodslPackage.VAINQUEUR__PLUS, oldPlus, plus));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyunodslPackage.VAINQUEUR__MANCHES:
        return getManches();
      case MyunodslPackage.VAINQUEUR__MOINS:
        return getMoins();
      case MyunodslPackage.VAINQUEUR__DERNIER:
        return getDernier();
      case MyunodslPackage.VAINQUEUR__PLUS:
        return getPlus();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyunodslPackage.VAINQUEUR__MANCHES:
        setManches((String)newValue);
        return;
      case MyunodslPackage.VAINQUEUR__MOINS:
        setMoins((String)newValue);
        return;
      case MyunodslPackage.VAINQUEUR__DERNIER:
        setDernier((String)newValue);
        return;
      case MyunodslPackage.VAINQUEUR__PLUS:
        setPlus((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.VAINQUEUR__MANCHES:
        setManches(MANCHES_EDEFAULT);
        return;
      case MyunodslPackage.VAINQUEUR__MOINS:
        setMoins(MOINS_EDEFAULT);
        return;
      case MyunodslPackage.VAINQUEUR__DERNIER:
        setDernier(DERNIER_EDEFAULT);
        return;
      case MyunodslPackage.VAINQUEUR__PLUS:
        setPlus(PLUS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyunodslPackage.VAINQUEUR__MANCHES:
        return MANCHES_EDEFAULT == null ? manches != null : !MANCHES_EDEFAULT.equals(manches);
      case MyunodslPackage.VAINQUEUR__MOINS:
        return MOINS_EDEFAULT == null ? moins != null : !MOINS_EDEFAULT.equals(moins);
      case MyunodslPackage.VAINQUEUR__DERNIER:
        return DERNIER_EDEFAULT == null ? dernier != null : !DERNIER_EDEFAULT.equals(dernier);
      case MyunodslPackage.VAINQUEUR__PLUS:
        return PLUS_EDEFAULT == null ? plus != null : !PLUS_EDEFAULT.equals(plus);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (manches: ");
    result.append(manches);
    result.append(", moins: ");
    result.append(moins);
    result.append(", dernier: ");
    result.append(dernier);
    result.append(", plus: ");
    result.append(plus);
    result.append(')');
    return result.toString();
  }

} //VainqueurImpl
