/*
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyunodslUiModule extends AbstractMyunodslUiModule {

	public MyunodslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
