/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.myunodsl.ui.internal.MyunodslActivator;

public class MyUnoDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MyunodslActivator.getInstance().getInjector("org.xtext.example.mydsl.MyUnoDsl");
	}

}
