/*
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyunodslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/example/myunodsl/parser/antlr/internal/InternalMyunodsl.tokens");
	}
}
