/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cartes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Cartes#getCa <em>Ca</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Cartes#getCc <em>Cc</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Cartes#getJpc <em>Jpc</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Cartes#getClj <em>Clj</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Cartes#getCdm <em>Cdm</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Cartes#getP <em>P</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCartes()
 * @model
 * @generated
 */
public interface Cartes extends EObject
{
  /**
   * Returns the value of the '<em><b>Ca</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ca</em>' attribute.
   * @see #setCa(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCartes_Ca()
   * @model
   * @generated
   */
  String getCa();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cartes#getCa <em>Ca</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ca</em>' attribute.
   * @see #getCa()
   * @generated
   */
  void setCa(String value);

  /**
   * Returns the value of the '<em><b>Cc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cc</em>' containment reference.
   * @see #setCc(Cumul_Cartes)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCartes_Cc()
   * @model containment="true"
   * @generated
   */
  Cumul_Cartes getCc();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cartes#getCc <em>Cc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cc</em>' containment reference.
   * @see #getCc()
   * @generated
   */
  void setCc(Cumul_Cartes value);

  /**
   * Returns the value of the '<em><b>Jpc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jpc</em>' containment reference.
   * @see #setJpc(Jouer_plusieurs_cartes)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCartes_Jpc()
   * @model containment="true"
   * @generated
   */
  Jouer_plusieurs_cartes getJpc();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cartes#getJpc <em>Jpc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jpc</em>' containment reference.
   * @see #getJpc()
   * @generated
   */
  void setJpc(Jouer_plusieurs_cartes value);

  /**
   * Returns the value of the '<em><b>Clj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clj</em>' containment reference.
   * @see #setClj(Couper_le_jeu)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCartes_Clj()
   * @model containment="true"
   * @generated
   */
  Couper_le_jeu getClj();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cartes#getClj <em>Clj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clj</em>' containment reference.
   * @see #getClj()
   * @generated
   */
  void setClj(Couper_le_jeu value);

  /**
   * Returns the value of the '<em><b>Cdm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cdm</em>' containment reference.
   * @see #setCdm(Changer_de_mains)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCartes_Cdm()
   * @model containment="true"
   * @generated
   */
  Changer_de_mains getCdm();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cartes#getCdm <em>Cdm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cdm</em>' containment reference.
   * @see #getCdm()
   * @generated
   */
  void setCdm(Changer_de_mains value);

  /**
   * Returns the value of the '<em><b>P</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' containment reference.
   * @see #setP(Plus4)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCartes_P()
   * @model containment="true"
   * @generated
   */
  Plus4 getP();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cartes#getP <em>P</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P</em>' containment reference.
   * @see #getP()
   * @generated
   */
  void setP(Plus4 value);

} // Cartes
