/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Changer de mains</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Changer_de_mains#getCdm <em>Cdm</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Changer_de_mains#getSev <em>Sev</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getChanger_de_mains()
 * @model
 * @generated
 */
public interface Changer_de_mains extends EObject
{
  /**
   * Returns the value of the '<em><b>Cdm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cdm</em>' attribute.
   * @see #setCdm(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getChanger_de_mains_Cdm()
   * @model
   * @generated
   */
  String getCdm();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Changer_de_mains#getCdm <em>Cdm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cdm</em>' attribute.
   * @see #getCdm()
   * @generated
   */
  void setCdm(String value);

  /**
   * Returns the value of the '<em><b>Sev</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sev</em>' containment reference.
   * @see #setSev(Seven_0)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getChanger_de_mains_Sev()
   * @model containment="true"
   * @generated
   */
  Seven_0 getSev();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Changer_de_mains#getSev <em>Sev</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sev</em>' containment reference.
   * @see #getSev()
   * @generated
   */
  void setSev(Seven_0 value);

} // Changer_de_mains
