/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cumul Cartes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Cumul_Cartes#getC <em>C</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Cumul_Cartes#getEff <em>Eff</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Cumul_Cartes#getPl2 <em>Pl2</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Cumul_Cartes#getPl4 <em>Pl4</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCumul_Cartes()
 * @model
 * @generated
 */
public interface Cumul_Cartes extends EObject
{
  /**
   * Returns the value of the '<em><b>C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' attribute.
   * @see #setC(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCumul_Cartes_C()
   * @model
   * @generated
   */
  String getC();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cumul_Cartes#getC <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' attribute.
   * @see #getC()
   * @generated
   */
  void setC(String value);

  /**
   * Returns the value of the '<em><b>Eff</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eff</em>' attribute.
   * @see #setEff(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCumul_Cartes_Eff()
   * @model
   * @generated
   */
  String getEff();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cumul_Cartes#getEff <em>Eff</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eff</em>' attribute.
   * @see #getEff()
   * @generated
   */
  void setEff(String value);

  /**
   * Returns the value of the '<em><b>Pl2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pl2</em>' containment reference.
   * @see #setPl2(PLUS_DEUX)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCumul_Cartes_Pl2()
   * @model containment="true"
   * @generated
   */
  PLUS_DEUX getPl2();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cumul_Cartes#getPl2 <em>Pl2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pl2</em>' containment reference.
   * @see #getPl2()
   * @generated
   */
  void setPl2(PLUS_DEUX value);

  /**
   * Returns the value of the '<em><b>Pl4</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pl4</em>' containment reference.
   * @see #setPl4(PLUS_QUATRE)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getCumul_Cartes_Pl4()
   * @model containment="true"
   * @generated
   */
  PLUS_QUATRE getPl4();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Cumul_Cartes#getPl4 <em>Pl4</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pl4</em>' containment reference.
   * @see #getPl4()
   * @generated
   */
  void setPl4(PLUS_QUATRE value);

} // Cumul_Cartes
