/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deroulement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Deroulement#getDer <em>Der</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Deroulement#getPiocher <em>Piocher</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Deroulement#getCartes <em>Cartes</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Deroulement#getPenaliter <em>Penaliter</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getDeroulement()
 * @model
 * @generated
 */
public interface Deroulement extends EObject
{
  /**
   * Returns the value of the '<em><b>Der</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Der</em>' attribute.
   * @see #setDer(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getDeroulement_Der()
   * @model
   * @generated
   */
  String getDer();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Deroulement#getDer <em>Der</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Der</em>' attribute.
   * @see #getDer()
   * @generated
   */
  void setDer(String value);

  /**
   * Returns the value of the '<em><b>Piocher</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Piocher</em>' containment reference.
   * @see #setPiocher(Piocher)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getDeroulement_Piocher()
   * @model containment="true"
   * @generated
   */
  Piocher getPiocher();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Deroulement#getPiocher <em>Piocher</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Piocher</em>' containment reference.
   * @see #getPiocher()
   * @generated
   */
  void setPiocher(Piocher value);

  /**
   * Returns the value of the '<em><b>Cartes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartes</em>' containment reference.
   * @see #setCartes(Cartes)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getDeroulement_Cartes()
   * @model containment="true"
   * @generated
   */
  Cartes getCartes();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Deroulement#getCartes <em>Cartes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cartes</em>' containment reference.
   * @see #getCartes()
   * @generated
   */
  void setCartes(Cartes value);

  /**
   * Returns the value of the '<em><b>Penaliter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Penaliter</em>' containment reference.
   * @see #setPenaliter(Penalite)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getDeroulement_Penaliter()
   * @model containment="true"
   * @generated
   */
  Penalite getPenaliter();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Deroulement#getPenaliter <em>Penaliter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Penaliter</em>' containment reference.
   * @see #getPenaliter()
   * @generated
   */
  void setPenaliter(Penalite value);

} // Deroulement
