/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equipe</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Equipe#getJeu <em>Jeu</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Equipe#getEq <em>Eq</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getEquipe()
 * @model
 * @generated
 */
public interface Equipe extends EObject
{
  /**
   * Returns the value of the '<em><b>Jeu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jeu</em>' attribute.
   * @see #setJeu(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getEquipe_Jeu()
   * @model
   * @generated
   */
  String getJeu();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Equipe#getJeu <em>Jeu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jeu</em>' attribute.
   * @see #getJeu()
   * @generated
   */
  void setJeu(String value);

  /**
   * Returns the value of the '<em><b>Eq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eq</em>' attribute.
   * @see #setEq(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getEquipe_Eq()
   * @model
   * @generated
   */
  String getEq();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Equipe#getEq <em>Eq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eq</em>' attribute.
   * @see #getEq()
   * @generated
   */
  void setEq(String value);

} // Equipe
