/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Fin#getF <em>F</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Fin#getFdm <em>Fdm</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Fin#getFdp <em>Fdp</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin()
 * @model
 * @generated
 */
public interface Fin extends EObject
{
  /**
   * Returns the value of the '<em><b>F</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' attribute.
   * @see #setF(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_F()
   * @model
   * @generated
   */
  String getF();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Fin#getF <em>F</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' attribute.
   * @see #getF()
   * @generated
   */
  void setF(String value);

  /**
   * Returns the value of the '<em><b>Fdm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fdm</em>' containment reference.
   * @see #setFdm(Fin_de_manche)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_Fdm()
   * @model containment="true"
   * @generated
   */
  Fin_de_manche getFdm();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Fin#getFdm <em>Fdm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fdm</em>' containment reference.
   * @see #getFdm()
   * @generated
   */
  void setFdm(Fin_de_manche value);

  /**
   * Returns the value of the '<em><b>Fdp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fdp</em>' containment reference.
   * @see #setFdp(Fin_de_partie)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_Fdp()
   * @model containment="true"
   * @generated
   */
  Fin_de_partie getFdp();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Fin#getFdp <em>Fdp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fdp</em>' containment reference.
   * @see #getFdp()
   * @generated
   */
  void setFdp(Fin_de_partie value);

} // Fin
