/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fin de manche</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Fin_de_manche#getFdmdu <em>Fdmdu</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Fin_de_manche#getDu <em>Du</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_de_manche()
 * @model
 * @generated
 */
public interface Fin_de_manche extends EObject
{
  /**
   * Returns the value of the '<em><b>Fdmdu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fdmdu</em>' attribute.
   * @see #setFdmdu(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_de_manche_Fdmdu()
   * @model
   * @generated
   */
  String getFdmdu();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Fin_de_manche#getFdmdu <em>Fdmdu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fdmdu</em>' attribute.
   * @see #getFdmdu()
   * @generated
   */
  void setFdmdu(String value);

  /**
   * Returns the value of the '<em><b>Du</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Du</em>' attribute.
   * @see #setDu(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_de_manche_Du()
   * @model
   * @generated
   */
  String getDu();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Fin_de_manche#getDu <em>Du</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Du</em>' attribute.
   * @see #getDu()
   * @generated
   */
  void setDu(String value);

} // Fin_de_manche
