/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fin de partie</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Fin_de_partie#getFdpv <em>Fdpv</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Fin_de_partie#getVaiqueur <em>Vaiqueur</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_de_partie()
 * @model
 * @generated
 */
public interface Fin_de_partie extends EObject
{
  /**
   * Returns the value of the '<em><b>Fdpv</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fdpv</em>' attribute.
   * @see #setFdpv(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_de_partie_Fdpv()
   * @model
   * @generated
   */
  String getFdpv();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Fin_de_partie#getFdpv <em>Fdpv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fdpv</em>' attribute.
   * @see #getFdpv()
   * @generated
   */
  void setFdpv(String value);

  /**
   * Returns the value of the '<em><b>Vaiqueur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vaiqueur</em>' containment reference.
   * @see #setVaiqueur(Vainqueur)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getFin_de_partie_Vaiqueur()
   * @model containment="true"
   * @generated
   */
  Vainqueur getVaiqueur();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Fin_de_partie#getVaiqueur <em>Vaiqueur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vaiqueur</em>' containment reference.
   * @see #getVaiqueur()
   * @generated
   */
  void setVaiqueur(Vainqueur value);

} // Fin_de_partie
