/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jouer plusieurs cartes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getJpc <em>Jpc</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getS <em>S</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getC <em>C</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getNb <em>Nb</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getCus <em>Cus</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getJouer_plusieurs_cartes()
 * @model
 * @generated
 */
public interface Jouer_plusieurs_cartes extends EObject
{
  /**
   * Returns the value of the '<em><b>Jpc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jpc</em>' attribute.
   * @see #setJpc(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getJouer_plusieurs_cartes_Jpc()
   * @model
   * @generated
   */
  String getJpc();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getJpc <em>Jpc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jpc</em>' attribute.
   * @see #getJpc()
   * @generated
   */
  void setJpc(String value);

  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference.
   * @see #setS(Suites)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getJouer_plusieurs_cartes_S()
   * @model containment="true"
   * @generated
   */
  Suites getS();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getS <em>S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' containment reference.
   * @see #getS()
   * @generated
   */
  void setS(Suites value);

  /**
   * Returns the value of the '<em><b>C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' attribute.
   * @see #setC(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getJouer_plusieurs_cartes_C()
   * @model
   * @generated
   */
  String getC();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getC <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' attribute.
   * @see #getC()
   * @generated
   */
  void setC(String value);

  /**
   * Returns the value of the '<em><b>Nb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb</em>' attribute.
   * @see #setNb(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getJouer_plusieurs_cartes_Nb()
   * @model
   * @generated
   */
  String getNb();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getNb <em>Nb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb</em>' attribute.
   * @see #getNb()
   * @generated
   */
  void setNb(String value);

  /**
   * Returns the value of the '<em><b>Cus</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cus</em>' containment reference.
   * @see #setCus(cartes_Uno_Speciales)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getJouer_plusieurs_cartes_Cus()
   * @model containment="true"
   * @generated
   */
  cartes_Uno_Speciales getCus();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Jouer_plusieurs_cartes#getCus <em>Cus</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cus</em>' containment reference.
   * @see #getCus()
   * @generated
   */
  void setCus(cartes_Uno_Speciales value);

} // Jouer_plusieurs_cartes
