/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Main#getMain <em>Main</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Main#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Main#getNbm <em>Nbm</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Main#getNbc <em>Nbc</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getMain()
 * @model
 * @generated
 */
public interface Main extends EObject
{
  /**
   * Returns the value of the '<em><b>Main</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' attribute.
   * @see #setMain(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getMain_Main()
   * @model
   * @generated
   */
  String getMain();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Main#getMain <em>Main</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' attribute.
   * @see #getMain()
   * @generated
   */
  void setMain(String value);

  /**
   * Returns the value of the '<em><b>Visibilite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibilite</em>' containment reference.
   * @see #setVisibilite(Visibilite)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getMain_Visibilite()
   * @model containment="true"
   * @generated
   */
  Visibilite getVisibilite();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Main#getVisibilite <em>Visibilite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibilite</em>' containment reference.
   * @see #getVisibilite()
   * @generated
   */
  void setVisibilite(Visibilite value);

  /**
   * Returns the value of the '<em><b>Nbm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbm</em>' containment reference.
   * @see #setNbm(Nombre_de_mains_de_depart)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getMain_Nbm()
   * @model containment="true"
   * @generated
   */
  Nombre_de_mains_de_depart getNbm();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Main#getNbm <em>Nbm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbm</em>' containment reference.
   * @see #getNbm()
   * @generated
   */
  void setNbm(Nombre_de_mains_de_depart value);

  /**
   * Returns the value of the '<em><b>Nbc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbc</em>' containment reference.
   * @see #setNbc(Nombre_de_cartes_de_depart)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getMain_Nbc()
   * @model containment="true"
   * @generated
   */
  Nombre_de_cartes_de_depart getNbc();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Main#getNbc <em>Nbc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbc</em>' containment reference.
   * @see #getNbc()
   * @generated
   */
  void setNbc(Nombre_de_cartes_de_depart value);

} // Main
