/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Meme nombre</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Meme_nombre#getMn <em>Mn</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Meme_nombre#getMc <em>Mc</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getMeme_nombre()
 * @model
 * @generated
 */
public interface Meme_nombre extends EObject
{
  /**
   * Returns the value of the '<em><b>Mn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mn</em>' attribute.
   * @see #setMn(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getMeme_nombre_Mn()
   * @model
   * @generated
   */
  String getMn();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Meme_nombre#getMn <em>Mn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mn</em>' attribute.
   * @see #getMn()
   * @generated
   */
  void setMn(String value);

  /**
   * Returns the value of the '<em><b>Mc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mc</em>' attribute.
   * @see #setMc(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getMeme_nombre_Mc()
   * @model
   * @generated
   */
  String getMc();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Meme_nombre#getMc <em>Mc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mc</em>' attribute.
   * @see #getMc()
   * @generated
   */
  void setMc(String value);

} // Meme_nombre
