/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.example.myunodsl.myunodsl.MyunodslPackage
 * @generated
 */
public interface MyunodslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyunodslFactory eINSTANCE = org.example.myunodsl.myunodsl.impl.MyunodslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Uno</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uno</em>'.
   * @generated
   */
  Uno createUno();

  /**
   * Returns a new object of class '<em>Configuration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Configuration</em>'.
   * @generated
   */
  Configuration createConfiguration();

  /**
   * Returns a new object of class '<em>Main</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main</em>'.
   * @generated
   */
  Main createMain();

  /**
   * Returns a new object of class '<em>Visibilite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Visibilite</em>'.
   * @generated
   */
  Visibilite createVisibilite();

  /**
   * Returns a new object of class '<em>Nombre de mains de depart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nombre de mains de depart</em>'.
   * @generated
   */
  Nombre_de_mains_de_depart createNombre_de_mains_de_depart();

  /**
   * Returns a new object of class '<em>Nombre de cartes de depart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nombre de cartes de depart</em>'.
   * @generated
   */
  Nombre_de_cartes_de_depart createNombre_de_cartes_de_depart();

  /**
   * Returns a new object of class '<em>Nombre de Talons de depart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nombre de Talons de depart</em>'.
   * @generated
   */
  Nombre_de_Talons_de_depart createNombre_de_Talons_de_depart();

  /**
   * Returns a new object of class '<em>Rotation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotation</em>'.
   * @generated
   */
  Rotation createRotation();

  /**
   * Returns a new object of class '<em>Nbjoueur</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nbjoueur</em>'.
   * @generated
   */
  Nbjoueur createNbjoueur();

  /**
   * Returns a new object of class '<em>Equipe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equipe</em>'.
   * @generated
   */
  Equipe createEquipe();

  /**
   * Returns a new object of class '<em>Deroulement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Deroulement</em>'.
   * @generated
   */
  Deroulement createDeroulement();

  /**
   * Returns a new object of class '<em>Piocher</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Piocher</em>'.
   * @generated
   */
  Piocher createPiocher();

  /**
   * Returns a new object of class '<em>Nombre de carte</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nombre de carte</em>'.
   * @generated
   */
  Nombre_de_carte createNombre_de_carte();

  /**
   * Returns a new object of class '<em>Cartes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cartes</em>'.
   * @generated
   */
  Cartes createCartes();

  /**
   * Returns a new object of class '<em>Cumul Cartes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cumul Cartes</em>'.
   * @generated
   */
  Cumul_Cartes createCumul_Cartes();

  /**
   * Returns a new object of class '<em>Jouer plusieurs cartes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Jouer plusieurs cartes</em>'.
   * @generated
   */
  Jouer_plusieurs_cartes createJouer_plusieurs_cartes();

  /**
   * Returns a new object of class '<em>Suites</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Suites</em>'.
   * @generated
   */
  Suites createSuites();

  /**
   * Returns a new object of class '<em>cartes Uno Speciales</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>cartes Uno Speciales</em>'.
   * @generated
   */
  cartes_Uno_Speciales createcartes_Uno_Speciales();

  /**
   * Returns a new object of class '<em>Plus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plus</em>'.
   * @generated
   */
  Plus createPlus();

  /**
   * Returns a new object of class '<em>Couper le jeu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Couper le jeu</em>'.
   * @generated
   */
  Couper_le_jeu createCouper_le_jeu();

  /**
   * Returns a new object of class '<em>Meme nombre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Meme nombre</em>'.
   * @generated
   */
  Meme_nombre createMeme_nombre();

  /**
   * Returns a new object of class '<em>Changer de mains</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Changer de mains</em>'.
   * @generated
   */
  Changer_de_mains createChanger_de_mains();

  /**
   * Returns a new object of class '<em>Seven 0</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Seven 0</em>'.
   * @generated
   */
  Seven_0 createSeven_0();

  /**
   * Returns a new object of class '<em>Plus4</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plus4</em>'.
   * @generated
   */
  Plus4 createPlus4();

  /**
   * Returns a new object of class '<em>Penalite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Penalite</em>'.
   * @generated
   */
  Penalite createPenalite();

  /**
   * Returns a new object of class '<em>Contestations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contestations</em>'.
   * @generated
   */
  Contestations createContestations();

  /**
   * Returns a new object of class '<em>Fin</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fin</em>'.
   * @generated
   */
  Fin createFin();

  /**
   * Returns a new object of class '<em>Fin de manche</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fin de manche</em>'.
   * @generated
   */
  Fin_de_manche createFin_de_manche();

  /**
   * Returns a new object of class '<em>Fin de partie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fin de partie</em>'.
   * @generated
   */
  Fin_de_partie createFin_de_partie();

  /**
   * Returns a new object of class '<em>Vainqueur</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vainqueur</em>'.
   * @generated
   */
  Vainqueur createVainqueur();

  /**
   * Returns a new object of class '<em>PLUS QUATRE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PLUS QUATRE</em>'.
   * @generated
   */
  PLUS_QUATRE createPLUS_QUATRE();

  /**
   * Returns a new object of class '<em>PLUS DEUX</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PLUS DEUX</em>'.
   * @generated
   */
  PLUS_DEUX createPLUS_DEUX();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyunodslPackage getMyunodslPackage();

} //MyunodslFactory
