/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nbjoueur</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Nbjoueur#getNbj <em>Nbj</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Nbjoueur#getN <em>N</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNbjoueur()
 * @model
 * @generated
 */
public interface Nbjoueur extends EObject
{
  /**
   * Returns the value of the '<em><b>Nbj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbj</em>' attribute.
   * @see #setNbj(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNbjoueur_Nbj()
   * @model
   * @generated
   */
  String getNbj();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Nbjoueur#getNbj <em>Nbj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbj</em>' attribute.
   * @see #getNbj()
   * @generated
   */
  void setNbj(String value);

  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNbjoueur_N()
   * @model
   * @generated
   */
  String getN();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Nbjoueur#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(String value);

} // Nbjoueur
