/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nombre de Talons de depart</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Nombre_de_Talons_de_depart#getNbtalon <em>Nbtalon</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Nombre_de_Talons_de_depart#getTalon <em>Talon</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_Talons_de_depart()
 * @model
 * @generated
 */
public interface Nombre_de_Talons_de_depart extends EObject
{
  /**
   * Returns the value of the '<em><b>Nbtalon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbtalon</em>' attribute.
   * @see #setNbtalon(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_Talons_de_depart_Nbtalon()
   * @model
   * @generated
   */
  String getNbtalon();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Nombre_de_Talons_de_depart#getNbtalon <em>Nbtalon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbtalon</em>' attribute.
   * @see #getNbtalon()
   * @generated
   */
  void setNbtalon(String value);

  /**
   * Returns the value of the '<em><b>Talon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Talon</em>' attribute.
   * @see #setTalon(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_Talons_de_depart_Talon()
   * @model
   * @generated
   */
  String getTalon();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Nombre_de_Talons_de_depart#getTalon <em>Talon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Talon</em>' attribute.
   * @see #getTalon()
   * @generated
   */
  void setTalon(String value);

} // Nombre_de_Talons_de_depart
