/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nombre de carte</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Nombre_de_carte#getNbc <em>Nbc</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Nombre_de_carte#getCa <em>Ca</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_carte()
 * @model
 * @generated
 */
public interface Nombre_de_carte extends EObject
{
  /**
   * Returns the value of the '<em><b>Nbc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbc</em>' attribute.
   * @see #setNbc(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_carte_Nbc()
   * @model
   * @generated
   */
  String getNbc();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Nombre_de_carte#getNbc <em>Nbc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbc</em>' attribute.
   * @see #getNbc()
   * @generated
   */
  void setNbc(String value);

  /**
   * Returns the value of the '<em><b>Ca</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ca</em>' attribute.
   * @see #setCa(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_carte_Ca()
   * @model
   * @generated
   */
  String getCa();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Nombre_de_carte#getCa <em>Ca</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ca</em>' attribute.
   * @see #getCa()
   * @generated
   */
  void setCa(String value);

} // Nombre_de_carte
