/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nombre de mains de depart</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Nombre_de_mains_de_depart#getNbm <em>Nbm</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Nombre_de_mains_de_depart#getMain <em>Main</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_mains_de_depart()
 * @model
 * @generated
 */
public interface Nombre_de_mains_de_depart extends EObject
{
  /**
   * Returns the value of the '<em><b>Nbm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbm</em>' attribute.
   * @see #setNbm(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_mains_de_depart_Nbm()
   * @model
   * @generated
   */
  String getNbm();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Nombre_de_mains_de_depart#getNbm <em>Nbm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbm</em>' attribute.
   * @see #getNbm()
   * @generated
   */
  void setNbm(String value);

  /**
   * Returns the value of the '<em><b>Main</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' attribute.
   * @see #setMain(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getNombre_de_mains_de_depart_Main()
   * @model
   * @generated
   */
  String getMain();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Nombre_de_mains_de_depart#getMain <em>Main</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' attribute.
   * @see #getMain()
   * @generated
   */
  void setMain(String value);

} // Nombre_de_mains_de_depart
