/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Penalite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Penalite#getPenalites <em>Penalites</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Penalite#getCi <em>Ci</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Penalite#getContestation <em>Contestation</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Penalite#getTpsl <em>Tpsl</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Penalite#getLtps <em>Ltps</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Penalite#getPenalite <em>Penalite</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPenalite()
 * @model
 * @generated
 */
public interface Penalite extends EObject
{
  /**
   * Returns the value of the '<em><b>Penalites</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Penalites</em>' attribute.
   * @see #setPenalites(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPenalite_Penalites()
   * @model
   * @generated
   */
  String getPenalites();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Penalite#getPenalites <em>Penalites</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Penalites</em>' attribute.
   * @see #getPenalites()
   * @generated
   */
  void setPenalites(String value);

  /**
   * Returns the value of the '<em><b>Ci</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ci</em>' attribute.
   * @see #setCi(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPenalite_Ci()
   * @model
   * @generated
   */
  String getCi();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Penalite#getCi <em>Ci</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ci</em>' attribute.
   * @see #getCi()
   * @generated
   */
  void setCi(String value);

  /**
   * Returns the value of the '<em><b>Contestation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contestation</em>' containment reference.
   * @see #setContestation(Contestations)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPenalite_Contestation()
   * @model containment="true"
   * @generated
   */
  Contestations getContestation();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Penalite#getContestation <em>Contestation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contestation</em>' containment reference.
   * @see #getContestation()
   * @generated
   */
  void setContestation(Contestations value);

  /**
   * Returns the value of the '<em><b>Tpsl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tpsl</em>' attribute.
   * @see #setTpsl(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPenalite_Tpsl()
   * @model
   * @generated
   */
  String getTpsl();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Penalite#getTpsl <em>Tpsl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tpsl</em>' attribute.
   * @see #getTpsl()
   * @generated
   */
  void setTpsl(String value);

  /**
   * Returns the value of the '<em><b>Ltps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ltps</em>' attribute.
   * @see #setLtps(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPenalite_Ltps()
   * @model
   * @generated
   */
  String getLtps();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Penalite#getLtps <em>Ltps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ltps</em>' attribute.
   * @see #getLtps()
   * @generated
   */
  void setLtps(String value);

  /**
   * Returns the value of the '<em><b>Penalite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Penalite</em>' attribute.
   * @see #setPenalite(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPenalite_Penalite()
   * @model
   * @generated
   */
  String getPenalite();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Penalite#getPenalite <em>Penalite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Penalite</em>' attribute.
   * @see #getPenalite()
   * @generated
   */
  void setPenalite(String value);

} // Penalite
