/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Piocher</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Piocher#getPio <em>Pio</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Piocher#getNbr <em>Nbr</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Piocher#getOptp <em>Optp</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPiocher()
 * @model
 * @generated
 */
public interface Piocher extends EObject
{
  /**
   * Returns the value of the '<em><b>Pio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pio</em>' attribute.
   * @see #setPio(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPiocher_Pio()
   * @model
   * @generated
   */
  String getPio();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Piocher#getPio <em>Pio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pio</em>' attribute.
   * @see #getPio()
   * @generated
   */
  void setPio(String value);

  /**
   * Returns the value of the '<em><b>Nbr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbr</em>' containment reference.
   * @see #setNbr(Nombre_de_carte)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPiocher_Nbr()
   * @model containment="true"
   * @generated
   */
  Nombre_de_carte getNbr();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Piocher#getNbr <em>Nbr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbr</em>' containment reference.
   * @see #getNbr()
   * @generated
   */
  void setNbr(Nombre_de_carte value);

  /**
   * Returns the value of the '<em><b>Optp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Optp</em>' attribute.
   * @see #setOptp(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPiocher_Optp()
   * @model
   * @generated
   */
  String getOptp();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Piocher#getOptp <em>Optp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Optp</em>' attribute.
   * @see #getOptp()
   * @generated
   */
  void setOptp(String value);

} // Piocher
