/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plus4</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Plus4#getPqq <em>Pqq</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Plus4#getPq <em>Pq</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Plus4#getSs <em>Ss</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Plus4#getIt <em>It</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Plus4#getP <em>P</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPlus4()
 * @model
 * @generated
 */
public interface Plus4 extends EObject
{
  /**
   * Returns the value of the '<em><b>Pqq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pqq</em>' containment reference.
   * @see #setPqq(PLUS_QUATRE)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPlus4_Pqq()
   * @model containment="true"
   * @generated
   */
  PLUS_QUATRE getPqq();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Plus4#getPqq <em>Pqq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pqq</em>' containment reference.
   * @see #getPqq()
   * @generated
   */
  void setPqq(PLUS_QUATRE value);

  /**
   * Returns the value of the '<em><b>Pq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pq</em>' containment reference.
   * @see #setPq(PLUS_QUATRE)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPlus4_Pq()
   * @model containment="true"
   * @generated
   */
  PLUS_QUATRE getPq();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Plus4#getPq <em>Pq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pq</em>' containment reference.
   * @see #getPq()
   * @generated
   */
  void setPq(PLUS_QUATRE value);

  /**
   * Returns the value of the '<em><b>Ss</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ss</em>' attribute.
   * @see #setSs(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPlus4_Ss()
   * @model
   * @generated
   */
  String getSs();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Plus4#getSs <em>Ss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ss</em>' attribute.
   * @see #getSs()
   * @generated
   */
  void setSs(String value);

  /**
   * Returns the value of the '<em><b>It</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>It</em>' attribute.
   * @see #setIt(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPlus4_It()
   * @model
   * @generated
   */
  String getIt();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Plus4#getIt <em>It</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>It</em>' attribute.
   * @see #getIt()
   * @generated
   */
  void setIt(String value);

  /**
   * Returns the value of the '<em><b>P</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' containment reference.
   * @see #setP(PLUS_QUATRE)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPlus4_P()
   * @model containment="true"
   * @generated
   */
  PLUS_QUATRE getP();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Plus4#getP <em>P</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P</em>' containment reference.
   * @see #getP()
   * @generated
   */
  void setP(PLUS_QUATRE value);

} // Plus4
