/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PLUS DEUX</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.PLUS_DEUX#getPld <em>Pld</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.PLUS_DEUX#getPd <em>Pd</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPLUS_DEUX()
 * @model
 * @generated
 */
public interface PLUS_DEUX extends EObject
{
  /**
   * Returns the value of the '<em><b>Pld</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pld</em>' attribute.
   * @see #setPld(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPLUS_DEUX_Pld()
   * @model
   * @generated
   */
  String getPld();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.PLUS_DEUX#getPld <em>Pld</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pld</em>' attribute.
   * @see #getPld()
   * @generated
   */
  void setPld(String value);

  /**
   * Returns the value of the '<em><b>Pd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pd</em>' attribute.
   * @see #setPd(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPLUS_DEUX_Pd()
   * @model
   * @generated
   */
  String getPd();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.PLUS_DEUX#getPd <em>Pd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pd</em>' attribute.
   * @see #getPd()
   * @generated
   */
  void setPd(String value);

} // PLUS_DEUX
