/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PLUS QUATRE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.PLUS_QUATRE#getPlq <em>Plq</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.PLUS_QUATRE#getPq <em>Pq</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPLUS_QUATRE()
 * @model
 * @generated
 */
public interface PLUS_QUATRE extends EObject
{
  /**
   * Returns the value of the '<em><b>Plq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plq</em>' attribute.
   * @see #setPlq(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPLUS_QUATRE_Plq()
   * @model
   * @generated
   */
  String getPlq();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.PLUS_QUATRE#getPlq <em>Plq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plq</em>' attribute.
   * @see #getPlq()
   * @generated
   */
  void setPlq(String value);

  /**
   * Returns the value of the '<em><b>Pq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pq</em>' attribute.
   * @see #setPq(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getPLUS_QUATRE_Pq()
   * @model
   * @generated
   */
  String getPq();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.PLUS_QUATRE#getPq <em>Pq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pq</em>' attribute.
   * @see #getPq()
   * @generated
   */
  void setPq(String value);

} // PLUS_QUATRE
