/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Seven 0</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Seven_0#getSe <em>Se</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Seven_0#getSept <em>Sept</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Seven_0#getZero <em>Zero</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getSeven_0()
 * @model
 * @generated
 */
public interface Seven_0 extends EObject
{
  /**
   * Returns the value of the '<em><b>Se</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Se</em>' attribute.
   * @see #setSe(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getSeven_0_Se()
   * @model
   * @generated
   */
  String getSe();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Seven_0#getSe <em>Se</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Se</em>' attribute.
   * @see #getSe()
   * @generated
   */
  void setSe(String value);

  /**
   * Returns the value of the '<em><b>Sept</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sept</em>' attribute.
   * @see #setSept(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getSeven_0_Sept()
   * @model
   * @generated
   */
  String getSept();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Seven_0#getSept <em>Sept</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sept</em>' attribute.
   * @see #getSept()
   * @generated
   */
  void setSept(String value);

  /**
   * Returns the value of the '<em><b>Zero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zero</em>' attribute.
   * @see #setZero(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getSeven_0_Zero()
   * @model
   * @generated
   */
  String getZero();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Seven_0#getZero <em>Zero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zero</em>' attribute.
   * @see #getZero()
   * @generated
   */
  void setZero(String value);

} // Seven_0
