/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Suites</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Suites#getSuites <em>Suites</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Suites#getSr <em>Sr</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getSuites()
 * @model
 * @generated
 */
public interface Suites extends EObject
{
  /**
   * Returns the value of the '<em><b>Suites</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Suites</em>' attribute.
   * @see #setSuites(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getSuites_Suites()
   * @model
   * @generated
   */
  String getSuites();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Suites#getSuites <em>Suites</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Suites</em>' attribute.
   * @see #getSuites()
   * @generated
   */
  void setSuites(String value);

  /**
   * Returns the value of the '<em><b>Sr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sr</em>' attribute.
   * @see #setSr(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getSuites_Sr()
   * @model
   * @generated
   */
  String getSr();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Suites#getSr <em>Sr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sr</em>' attribute.
   * @see #getSr()
   * @generated
   */
  void setSr(String value);

} // Suites
