/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Uno#getUn <em>Un</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Uno#getConf <em>Conf</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Uno#getDeroulement <em>Deroulement</em>}</li>
 *   <li>{@link org.example.myunodsl.myunodsl.Uno#getFin <em>Fin</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getUno()
 * @model
 * @generated
 */
public interface Uno extends EObject
{
  /**
   * Returns the value of the '<em><b>Un</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Un</em>' attribute.
   * @see #setUn(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getUno_Un()
   * @model
   * @generated
   */
  String getUn();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Uno#getUn <em>Un</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Un</em>' attribute.
   * @see #getUn()
   * @generated
   */
  void setUn(String value);

  /**
   * Returns the value of the '<em><b>Conf</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conf</em>' containment reference.
   * @see #setConf(Configuration)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getUno_Conf()
   * @model containment="true"
   * @generated
   */
  Configuration getConf();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Uno#getConf <em>Conf</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conf</em>' containment reference.
   * @see #getConf()
   * @generated
   */
  void setConf(Configuration value);

  /**
   * Returns the value of the '<em><b>Deroulement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deroulement</em>' containment reference.
   * @see #setDeroulement(Deroulement)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getUno_Deroulement()
   * @model containment="true"
   * @generated
   */
  Deroulement getDeroulement();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Uno#getDeroulement <em>Deroulement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deroulement</em>' containment reference.
   * @see #getDeroulement()
   * @generated
   */
  void setDeroulement(Deroulement value);

  /**
   * Returns the value of the '<em><b>Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin</em>' containment reference.
   * @see #setFin(Fin)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getUno_Fin()
   * @model containment="true"
   * @generated
   */
  Fin getFin();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Uno#getFin <em>Fin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin</em>' containment reference.
   * @see #getFin()
   * @generated
   */
  void setFin(Fin value);

} // Uno
