/**
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.myunodsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Visibilite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.myunodsl.myunodsl.Visibilite#getVis <em>Vis</em>}</li>
 * </ul>
 *
 * @see org.example.myunodsl.myunodsl.MyunodslPackage#getVisibilite()
 * @model
 * @generated
 */
public interface Visibilite extends EObject
{
  /**
   * Returns the value of the '<em><b>Vis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vis</em>' attribute.
   * @see #setVis(String)
   * @see org.example.myunodsl.myunodsl.MyunodslPackage#getVisibilite_Vis()
   * @model
   * @generated
   */
  String getVis();

  /**
   * Sets the value of the '{@link org.example.myunodsl.myunodsl.Visibilite#getVis <em>Vis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vis</em>' attribute.
   * @see #getVis()
   * @generated
   */
  void setVis(String value);

} // Visibilite
