/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cartes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getCc <em>Cc</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getJpc <em>Jpc</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getClj <em>Clj</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getCdm <em>Cdm</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getP4 <em>P4</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getCartes()
 * @model
 * @generated
 */
public interface Cartes extends EObject
{
  /**
   * Returns the value of the '<em><b>Cc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cc</em>' containment reference.
   * @see #setCc(Cumul_Cartes)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getCartes_Cc()
   * @model containment="true"
   * @generated
   */
  Cumul_Cartes getCc();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getCc <em>Cc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cc</em>' containment reference.
   * @see #getCc()
   * @generated
   */
  void setCc(Cumul_Cartes value);

  /**
   * Returns the value of the '<em><b>Jpc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jpc</em>' containment reference.
   * @see #setJpc(Jouer_plusieurs_cartes)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getCartes_Jpc()
   * @model containment="true"
   * @generated
   */
  Jouer_plusieurs_cartes getJpc();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getJpc <em>Jpc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jpc</em>' containment reference.
   * @see #getJpc()
   * @generated
   */
  void setJpc(Jouer_plusieurs_cartes value);

  /**
   * Returns the value of the '<em><b>Clj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clj</em>' attribute.
   * @see #setClj(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getCartes_Clj()
   * @model
   * @generated
   */
  String getClj();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getClj <em>Clj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clj</em>' attribute.
   * @see #getClj()
   * @generated
   */
  void setClj(String value);

  /**
   * Returns the value of the '<em><b>Cdm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cdm</em>' attribute.
   * @see #setCdm(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getCartes_Cdm()
   * @model
   * @generated
   */
  String getCdm();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getCdm <em>Cdm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cdm</em>' attribute.
   * @see #getCdm()
   * @generated
   */
  void setCdm(String value);

  /**
   * Returns the value of the '<em><b>P4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P4</em>' attribute.
   * @see #setP4(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getCartes_P4()
   * @model
   * @generated
   */
  String getP4();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Cartes#getP4 <em>P4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P4</em>' attribute.
   * @see #getP4()
   * @generated
   */
  void setP4(String value);

} // Cartes
