/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deroulement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Deroulement#getPiocher <em>Piocher</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Deroulement#getCartes <em>Cartes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Deroulement#getPen <em>Pen</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getDeroulement()
 * @model
 * @generated
 */
public interface Deroulement extends EObject
{
  /**
   * Returns the value of the '<em><b>Piocher</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Piocher</em>' containment reference.
   * @see #setPiocher(Piocher)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getDeroulement_Piocher()
   * @model containment="true"
   * @generated
   */
  Piocher getPiocher();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Deroulement#getPiocher <em>Piocher</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Piocher</em>' containment reference.
   * @see #getPiocher()
   * @generated
   */
  void setPiocher(Piocher value);

  /**
   * Returns the value of the '<em><b>Cartes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartes</em>' containment reference.
   * @see #setCartes(Cartes)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getDeroulement_Cartes()
   * @model containment="true"
   * @generated
   */
  Cartes getCartes();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Deroulement#getCartes <em>Cartes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cartes</em>' containment reference.
   * @see #getCartes()
   * @generated
   */
  void setCartes(Cartes value);

  /**
   * Returns the value of the '<em><b>Pen</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myUnoDsl.Penalite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pen</em>' containment reference list.
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getDeroulement_Pen()
   * @model containment="true"
   * @generated
   */
  EList<Penalite> getPen();

} // Deroulement
