/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jouer plusieurs cartes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Jouer_plusieurs_cartes#getS <em>S</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Jouer_plusieurs_cartes#getCus <em>Cus</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getJouer_plusieurs_cartes()
 * @model
 * @generated
 */
public interface Jouer_plusieurs_cartes extends EObject
{
  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference.
   * @see #setS(Suites)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getJouer_plusieurs_cartes_S()
   * @model containment="true"
   * @generated
   */
  Suites getS();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Jouer_plusieurs_cartes#getS <em>S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' containment reference.
   * @see #getS()
   * @generated
   */
  void setS(Suites value);

  /**
   * Returns the value of the '<em><b>Cus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cus</em>' attribute.
   * @see #setCus(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getJouer_plusieurs_cartes_Cus()
   * @model
   * @generated
   */
  String getCus();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Jouer_plusieurs_cartes#getCus <em>Cus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cus</em>' attribute.
   * @see #getCus()
   * @generated
   */
  void setCus(String value);

} // Jouer_plusieurs_cartes
