/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Main#getNbt <em>Nbt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Main#getRot <em>Rot</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Main#getEqu <em>Equ</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Main#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Main#getNbm <em>Nbm</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Main#getNbc <em>Nbc</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getMain()
 * @model
 * @generated
 */
public interface Main extends Configuration
{
  /**
   * Returns the value of the '<em><b>Nbt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbt</em>' attribute.
   * @see #setNbt(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getMain_Nbt()
   * @model
   * @generated
   */
  String getNbt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Main#getNbt <em>Nbt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbt</em>' attribute.
   * @see #getNbt()
   * @generated
   */
  void setNbt(String value);

  /**
   * Returns the value of the '<em><b>Rot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rot</em>' attribute.
   * @see #setRot(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getMain_Rot()
   * @model
   * @generated
   */
  String getRot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Main#getRot <em>Rot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rot</em>' attribute.
   * @see #getRot()
   * @generated
   */
  void setRot(String value);

  /**
   * Returns the value of the '<em><b>Equ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equ</em>' attribute.
   * @see #setEqu(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getMain_Equ()
   * @model
   * @generated
   */
  String getEqu();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Main#getEqu <em>Equ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Equ</em>' attribute.
   * @see #getEqu()
   * @generated
   */
  void setEqu(String value);

  /**
   * Returns the value of the '<em><b>Visibilite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibilite</em>' attribute.
   * @see #setVisibilite(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getMain_Visibilite()
   * @model
   * @generated
   */
  String getVisibilite();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Main#getVisibilite <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibilite</em>' attribute.
   * @see #getVisibilite()
   * @generated
   */
  void setVisibilite(String value);

  /**
   * Returns the value of the '<em><b>Nbm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbm</em>' attribute.
   * @see #setNbm(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getMain_Nbm()
   * @model
   * @generated
   */
  String getNbm();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Main#getNbm <em>Nbm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbm</em>' attribute.
   * @see #getNbm()
   * @generated
   */
  void setNbm(String value);

  /**
   * Returns the value of the '<em><b>Nbc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbc</em>' attribute.
   * @see #setNbc(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getMain_Nbc()
   * @model
   * @generated
   */
  String getNbc();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Main#getNbc <em>Nbc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nbc</em>' attribute.
   * @see #getNbc()
   * @generated
   */
  void setNbc(String value);

} // Main
