/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage
 * @generated
 */
public interface MyUnoDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyUnoDslFactory eINSTANCE = org.xtext.example.mydsl.myUnoDsl.impl.MyUnoDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Configuration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Configuration</em>'.
   * @generated
   */
  Configuration createConfiguration();

  /**
   * Returns a new object of class '<em>Main</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main</em>'.
   * @generated
   */
  Main createMain();

  /**
   * Returns a new object of class '<em>Deroulement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Deroulement</em>'.
   * @generated
   */
  Deroulement createDeroulement();

  /**
   * Returns a new object of class '<em>Piocher</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Piocher</em>'.
   * @generated
   */
  Piocher createPiocher();

  /**
   * Returns a new object of class '<em>Cartes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cartes</em>'.
   * @generated
   */
  Cartes createCartes();

  /**
   * Returns a new object of class '<em>Cumul Cartes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cumul Cartes</em>'.
   * @generated
   */
  Cumul_Cartes createCumul_Cartes();

  /**
   * Returns a new object of class '<em>Jouer plusieurs cartes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Jouer plusieurs cartes</em>'.
   * @generated
   */
  Jouer_plusieurs_cartes createJouer_plusieurs_cartes();

  /**
   * Returns a new object of class '<em>Suites</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Suites</em>'.
   * @generated
   */
  Suites createSuites();

  /**
   * Returns a new object of class '<em>Penalite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Penalite</em>'.
   * @generated
   */
  Penalite createPenalite();

  /**
   * Returns a new object of class '<em>Fin</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fin</em>'.
   * @generated
   */
  Fin createFin();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyUnoDslPackage getMyUnoDslPackage();

} //MyUnoDslFactory
