/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Penalite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.Penalite#getPenalite <em>Penalite</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getPenalite()
 * @model
 * @generated
 */
public interface Penalite extends EObject
{
  /**
   * Returns the value of the '<em><b>Penalite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Penalite</em>' attribute.
   * @see #setPenalite(String)
   * @see org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage#getPenalite_Penalite()
   * @model
   * @generated
   */
  String getPenalite();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myUnoDsl.Penalite#getPenalite <em>Penalite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Penalite</em>' attribute.
   * @see #getPenalite()
   * @generated
   */
  void setPenalite(String value);

} // Penalite
