/*
 * generated by Xtext 2.23.0
 */
package org.example.myunodsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyunodslScopeProvider extends DelegatingScopeProvider {
}
