/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myUnoDsl.Cumul_Cartes;
import org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cumul Cartes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.Cumul_CartesImpl#getEff <em>Eff</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.Cumul_CartesImpl#getCcp <em>Ccp</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Cumul_CartesImpl extends MinimalEObjectImpl.Container implements Cumul_Cartes
{
  /**
   * The default value of the '{@link #getEff() <em>Eff</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEff()
   * @generated
   * @ordered
   */
  protected static final String EFF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEff() <em>Eff</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEff()
   * @generated
   * @ordered
   */
  protected String eff = EFF_EDEFAULT;

  /**
   * The default value of the '{@link #getCcp() <em>Ccp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCcp()
   * @generated
   * @ordered
   */
  protected static final String CCP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCcp() <em>Ccp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCcp()
   * @generated
   * @ordered
   */
  protected String ccp = CCP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Cumul_CartesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoDslPackage.Literals.CUMUL_CARTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEff()
  {
    return eff;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEff(String newEff)
  {
    String oldEff = eff;
    eff = newEff;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.CUMUL_CARTES__EFF, oldEff, eff));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCcp()
  {
    return ccp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCcp(String newCcp)
  {
    String oldCcp = ccp;
    ccp = newCcp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.CUMUL_CARTES__CCP, oldCcp, ccp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.CUMUL_CARTES__EFF:
        return getEff();
      case MyUnoDslPackage.CUMUL_CARTES__CCP:
        return getCcp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.CUMUL_CARTES__EFF:
        setEff((String)newValue);
        return;
      case MyUnoDslPackage.CUMUL_CARTES__CCP:
        setCcp((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.CUMUL_CARTES__EFF:
        setEff(EFF_EDEFAULT);
        return;
      case MyUnoDslPackage.CUMUL_CARTES__CCP:
        setCcp(CCP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.CUMUL_CARTES__EFF:
        return EFF_EDEFAULT == null ? eff != null : !EFF_EDEFAULT.equals(eff);
      case MyUnoDslPackage.CUMUL_CARTES__CCP:
        return CCP_EDEFAULT == null ? ccp != null : !CCP_EDEFAULT.equals(ccp);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (eff: ");
    result.append(eff);
    result.append(", ccp: ");
    result.append(ccp);
    result.append(')');
    return result.toString();
  }

} //Cumul_CartesImpl
