/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myUnoDsl.Jouer_plusieurs_cartes;
import org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage;
import org.xtext.example.mydsl.myUnoDsl.Suites;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Jouer plusieurs cartes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.Jouer_plusieurs_cartesImpl#getS <em>S</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.Jouer_plusieurs_cartesImpl#getCus <em>Cus</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Jouer_plusieurs_cartesImpl extends MinimalEObjectImpl.Container implements Jouer_plusieurs_cartes
{
  /**
   * The cached value of the '{@link #getS() <em>S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getS()
   * @generated
   * @ordered
   */
  protected Suites s;

  /**
   * The default value of the '{@link #getCus() <em>Cus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCus()
   * @generated
   * @ordered
   */
  protected static final String CUS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCus() <em>Cus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCus()
   * @generated
   * @ordered
   */
  protected String cus = CUS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Jouer_plusieurs_cartesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoDslPackage.Literals.JOUER_PLUSIEURS_CARTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Suites getS()
  {
    return s;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetS(Suites newS, NotificationChain msgs)
  {
    Suites oldS = s;
    s = newS;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S, oldS, newS);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setS(Suites newS)
  {
    if (newS != s)
    {
      NotificationChain msgs = null;
      if (s != null)
        msgs = ((InternalEObject)s).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S, null, msgs);
      if (newS != null)
        msgs = ((InternalEObject)newS).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S, null, msgs);
      msgs = basicSetS(newS, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S, newS, newS));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCus()
  {
    return cus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCus(String newCus)
  {
    String oldCus = cus;
    cus = newCus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__CUS, oldCus, cus));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S:
        return basicSetS(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S:
        return getS();
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        return getCus();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S:
        setS((Suites)newValue);
        return;
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        setCus((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S:
        setS((Suites)null);
        return;
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        setCus(CUS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__S:
        return s != null;
      case MyUnoDslPackage.JOUER_PLUSIEURS_CARTES__CUS:
        return CUS_EDEFAULT == null ? cus != null : !CUS_EDEFAULT.equals(cus);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cus: ");
    result.append(cus);
    result.append(')');
    return result.toString();
  }

} //Jouer_plusieurs_cartesImpl
