/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myUnoDsl.Main;
import org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Main</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.MainImpl#getNbt <em>Nbt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.MainImpl#getRot <em>Rot</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.MainImpl#getEqu <em>Equ</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.MainImpl#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.MainImpl#getNbm <em>Nbm</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.MainImpl#getNbc <em>Nbc</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MainImpl extends ConfigurationImpl implements Main
{
  /**
   * The default value of the '{@link #getNbt() <em>Nbt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbt()
   * @generated
   * @ordered
   */
  protected static final String NBT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNbt() <em>Nbt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbt()
   * @generated
   * @ordered
   */
  protected String nbt = NBT_EDEFAULT;

  /**
   * The default value of the '{@link #getRot() <em>Rot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRot()
   * @generated
   * @ordered
   */
  protected static final String ROT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRot() <em>Rot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRot()
   * @generated
   * @ordered
   */
  protected String rot = ROT_EDEFAULT;

  /**
   * The default value of the '{@link #getEqu() <em>Equ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEqu()
   * @generated
   * @ordered
   */
  protected static final String EQU_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEqu() <em>Equ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEqu()
   * @generated
   * @ordered
   */
  protected String equ = EQU_EDEFAULT;

  /**
   * The default value of the '{@link #getVisibilite() <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibilite()
   * @generated
   * @ordered
   */
  protected static final String VISIBILITE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVisibilite() <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibilite()
   * @generated
   * @ordered
   */
  protected String visibilite = VISIBILITE_EDEFAULT;

  /**
   * The default value of the '{@link #getNbm() <em>Nbm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbm()
   * @generated
   * @ordered
   */
  protected static final String NBM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNbm() <em>Nbm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbm()
   * @generated
   * @ordered
   */
  protected String nbm = NBM_EDEFAULT;

  /**
   * The default value of the '{@link #getNbc() <em>Nbc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbc()
   * @generated
   * @ordered
   */
  protected static final String NBC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNbc() <em>Nbc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbc()
   * @generated
   * @ordered
   */
  protected String nbc = NBC_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoDslPackage.Literals.MAIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNbt()
  {
    return nbt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbt(String newNbt)
  {
    String oldNbt = nbt;
    nbt = newNbt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.MAIN__NBT, oldNbt, nbt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRot()
  {
    return rot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRot(String newRot)
  {
    String oldRot = rot;
    rot = newRot;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.MAIN__ROT, oldRot, rot));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEqu()
  {
    return equ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEqu(String newEqu)
  {
    String oldEqu = equ;
    equ = newEqu;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.MAIN__EQU, oldEqu, equ));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVisibilite()
  {
    return visibilite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibilite(String newVisibilite)
  {
    String oldVisibilite = visibilite;
    visibilite = newVisibilite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.MAIN__VISIBILITE, oldVisibilite, visibilite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNbm()
  {
    return nbm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbm(String newNbm)
  {
    String oldNbm = nbm;
    nbm = newNbm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.MAIN__NBM, oldNbm, nbm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNbc()
  {
    return nbc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbc(String newNbc)
  {
    String oldNbc = nbc;
    nbc = newNbc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.MAIN__NBC, oldNbc, nbc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.MAIN__NBT:
        return getNbt();
      case MyUnoDslPackage.MAIN__ROT:
        return getRot();
      case MyUnoDslPackage.MAIN__EQU:
        return getEqu();
      case MyUnoDslPackage.MAIN__VISIBILITE:
        return getVisibilite();
      case MyUnoDslPackage.MAIN__NBM:
        return getNbm();
      case MyUnoDslPackage.MAIN__NBC:
        return getNbc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.MAIN__NBT:
        setNbt((String)newValue);
        return;
      case MyUnoDslPackage.MAIN__ROT:
        setRot((String)newValue);
        return;
      case MyUnoDslPackage.MAIN__EQU:
        setEqu((String)newValue);
        return;
      case MyUnoDslPackage.MAIN__VISIBILITE:
        setVisibilite((String)newValue);
        return;
      case MyUnoDslPackage.MAIN__NBM:
        setNbm((String)newValue);
        return;
      case MyUnoDslPackage.MAIN__NBC:
        setNbc((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.MAIN__NBT:
        setNbt(NBT_EDEFAULT);
        return;
      case MyUnoDslPackage.MAIN__ROT:
        setRot(ROT_EDEFAULT);
        return;
      case MyUnoDslPackage.MAIN__EQU:
        setEqu(EQU_EDEFAULT);
        return;
      case MyUnoDslPackage.MAIN__VISIBILITE:
        setVisibilite(VISIBILITE_EDEFAULT);
        return;
      case MyUnoDslPackage.MAIN__NBM:
        setNbm(NBM_EDEFAULT);
        return;
      case MyUnoDslPackage.MAIN__NBC:
        setNbc(NBC_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.MAIN__NBT:
        return NBT_EDEFAULT == null ? nbt != null : !NBT_EDEFAULT.equals(nbt);
      case MyUnoDslPackage.MAIN__ROT:
        return ROT_EDEFAULT == null ? rot != null : !ROT_EDEFAULT.equals(rot);
      case MyUnoDslPackage.MAIN__EQU:
        return EQU_EDEFAULT == null ? equ != null : !EQU_EDEFAULT.equals(equ);
      case MyUnoDslPackage.MAIN__VISIBILITE:
        return VISIBILITE_EDEFAULT == null ? visibilite != null : !VISIBILITE_EDEFAULT.equals(visibilite);
      case MyUnoDslPackage.MAIN__NBM:
        return NBM_EDEFAULT == null ? nbm != null : !NBM_EDEFAULT.equals(nbm);
      case MyUnoDslPackage.MAIN__NBC:
        return NBC_EDEFAULT == null ? nbc != null : !NBC_EDEFAULT.equals(nbc);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nbt: ");
    result.append(nbt);
    result.append(", rot: ");
    result.append(rot);
    result.append(", equ: ");
    result.append(equ);
    result.append(", visibilite: ");
    result.append(visibilite);
    result.append(", nbm: ");
    result.append(nbm);
    result.append(", nbc: ");
    result.append(nbc);
    result.append(')');
    return result.toString();
  }

} //MainImpl
