/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage;
import org.xtext.example.mydsl.myUnoDsl.Piocher;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Piocher</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.PiocherImpl#getNbr <em>Nbr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.PiocherImpl#getOptp <em>Optp</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PiocherImpl extends MinimalEObjectImpl.Container implements Piocher
{
  /**
   * The default value of the '{@link #getNbr() <em>Nbr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbr()
   * @generated
   * @ordered
   */
  protected static final String NBR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNbr() <em>Nbr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbr()
   * @generated
   * @ordered
   */
  protected String nbr = NBR_EDEFAULT;

  /**
   * The default value of the '{@link #getOptp() <em>Optp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOptp()
   * @generated
   * @ordered
   */
  protected static final String OPTP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOptp() <em>Optp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOptp()
   * @generated
   * @ordered
   */
  protected String optp = OPTP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PiocherImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoDslPackage.Literals.PIOCHER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNbr()
  {
    return nbr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbr(String newNbr)
  {
    String oldNbr = nbr;
    nbr = newNbr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.PIOCHER__NBR, oldNbr, nbr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOptp()
  {
    return optp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOptp(String newOptp)
  {
    String oldOptp = optp;
    optp = newOptp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.PIOCHER__OPTP, oldOptp, optp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.PIOCHER__NBR:
        return getNbr();
      case MyUnoDslPackage.PIOCHER__OPTP:
        return getOptp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.PIOCHER__NBR:
        setNbr((String)newValue);
        return;
      case MyUnoDslPackage.PIOCHER__OPTP:
        setOptp((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.PIOCHER__NBR:
        setNbr(NBR_EDEFAULT);
        return;
      case MyUnoDslPackage.PIOCHER__OPTP:
        setOptp(OPTP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.PIOCHER__NBR:
        return NBR_EDEFAULT == null ? nbr != null : !NBR_EDEFAULT.equals(nbr);
      case MyUnoDslPackage.PIOCHER__OPTP:
        return OPTP_EDEFAULT == null ? optp != null : !OPTP_EDEFAULT.equals(optp);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nbr: ");
    result.append(nbr);
    result.append(", optp: ");
    result.append(optp);
    result.append(')');
    return result.toString();
  }

} //PiocherImpl
