/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myUnoDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myUnoDsl.MyUnoDslPackage;
import org.xtext.example.mydsl.myUnoDsl.Suites;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Suites</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myUnoDsl.impl.SuitesImpl#getSr <em>Sr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SuitesImpl extends MinimalEObjectImpl.Container implements Suites
{
  /**
   * The default value of the '{@link #getSr() <em>Sr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSr()
   * @generated
   * @ordered
   */
  protected static final String SR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSr() <em>Sr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSr()
   * @generated
   * @ordered
   */
  protected String sr = SR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuitesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoDslPackage.Literals.SUITES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSr()
  {
    return sr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSr(String newSr)
  {
    String oldSr = sr;
    sr = newSr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoDslPackage.SUITES__SR, oldSr, sr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.SUITES__SR:
        return getSr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.SUITES__SR:
        setSr((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.SUITES__SR:
        setSr(SR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoDslPackage.SUITES__SR:
        return SR_EDEFAULT == null ? sr != null : !SR_EDEFAULT.equals(sr);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (sr: ");
    result.append(sr);
    result.append(')');
    return result.toString();
  }

} //SuitesImpl
